package main

import (
	"flag"
	"fmt"
	"strings"

	"github.com/erikbryant/waffle/board"
	"github.com/erikbryant/waffle/pathfinder"
	"github.com/erikbryant/waffle/solver"
)

type TestCase struct {
	serial string
	index  int
}

var (
	deluxeWaffles = []TestCase{
		{"ovamtcas a e nstaaoptd r t raoieterh e m poverdno/ywgygwwy w y wgwgwgygw g g wgygwgwgw w w wwwgwgyy", 113},
		{"dleeiaep u a aerpenoex e e xtrntryma g l nssegdda/ywgwgwyy w w ygwgggwgw w y wgwgggwgy w w wwwgwgyy", 112},
		{"ohfneera d s lchuaisgp n t ktmdtosei p e aeireers/wygwgyyw w w wgwgygygw g g wgwgwgwgy w w wywgwgwy", 111},
		{"lsfaetad l s tbrrclpre s i etdalpeek m e onuemego/ywgwgywy w y ygwgwgwgy g g wgwgygwgw w w ywwgwgww", 110},
		{"egcaaedo e i srpmxneee p e dhracskti e a ncosdabm/yygygwyw w y wgwgwgwgy g g wgwgwgwgw w w wywgygyw", 109},
		{"rrttadel i u mpiatoanc o o sottraleg p v rdcrcoii/ywgygyyy w w wgwgggwgw y w ygwgggwgw w y wywgwgyy", 108},
		{"cdirpmaf l e etsmbouae e f ohrrvelts p d dialotoe/yygwgwwy w w ygwgggwgy w w wgwgggwgw w w yywgwgwy", 107},
		{"ngdnefbc d n iansratns s m eeeitidet o s toxrmeaa/ywgwgwww w y wgwgwgygy g g wgwgwgygy y w yywgwgwy", 106},
		{"maceolde s u rciaotnce a s lahmleesx n h adedilmi/ywgygyyy w w wgygggwgw w w wgwgggwgy w w yyygwgyw", 105},
		{"yracieou l o itnaitrre s o bcldenned s a nstneeen/wwgwgyyw w w wgwgggygy w w wgwgggwgy w w yywgygww", 104},
		{"maoeercm w a lalauehrr t r ibtotnsey t r oesyrlsl/ywgwgwyw w y ygwgygwgy g g wgwgwgwgw w w wywgygwy", 103},
		{"ectehuea d e ulandtrco k e atrakfrli s h iaadelut/yygwgwyw w w wgygwgwgy g g ygygwgwgw w w wwwgygwy", 102},
		{"ulneicyp r h eaitacede e i nhlavisrg c a tueelrnl/ywgygwyy w y ygygggwgw w w wgwgggwgy y w wwwgygwy", 101},
		{"bearhbse n r eopserees d c vsdecicsa n e oubsdees/yygwgwyy w w ygwgggwgw w w wgwgggwgy w y wywgygyw", 100},
		{"raanigeo v r earrostln c l egoaniler l t hadyylrt/ywgygyww w w wgwgggwgw w y wgwgggwgy y y wywgygyy", 99},
		{"enotadss r g gfttpensi d r eimoaanet c n lluroevi/ywgwgyww w y wgwgwgygy g g ygwgwgwgy w w wywgwgww", 98},
		{"cordvddn l d evwnegert a i rsuomarha u a aiinctae/wwgwgwyw w w ygwgggwgw w w wgwgggwgy y y wywgwgyy", 97},
		{"einnoiup r l isoaniile i y edgiftmdr e l snegtdre/yygwgwyw y w ygwgggwgw w w wgwgggwgy y w yywgwgyw", 96},
		{"gofbaiei t f dbniocvei t n yshawerde u a reaertrl/wygygwwy y w ygwgggwgw w y wgwgggwgw w w yyygygww", 95},
		{"ihgntuic d e suhatirma z c utiihklrr e a rnegeten/yygygwww w y wgwgwgygw g g ygwgygwgy w w wwwgwgwy", 94},
		{"lhllgini a l csnatlotl d l yaainaeeo l g ttrgttre/ywgygywy w w wgwgwgwgy g g ygwgwgwgw w w yywgwgww", 93},
		{"atoregrd e i earemosec l p ssnabieds p r nrneemrt/wwgygwyy w w ygwgggwgw w w ygwgggygw y w yywgygyw", 92},
		{"lveiadae p r rchasscce i e edtsseetl l n uotdxeie/yygwgwwy y y wgwgggwgy w w ygwgggwgw y w wywgwgwy", 91},
		{"motnosli m l kcwuntuyr r e rasamadto r n npaiotcs/ywgwgwwy y y ygwgggwgw w w ygwgggygw w w ywwgygwy", 90},
		{"ctuniuaa e a elltiilee e t ptdraignh o o dlsdtlon/wwgygwyw y y ygwgwgwgw g g wgwgwgwgy w w yywgwgww", 89},
		{"nnoaepot e u iontgrrwa h r raschioep i r coeligvn/ywgwgyyw w w wgwgggwgw w w ygwgggwgy y w wyygwgwy", 88},
		{"anvlleoh r c dmdneaiae i t edalehane r y oolatrip/yygwgyyw w w ygygwgwgw g g ygwgwgwgw w w wywgwgww", 87},
		{"insufnoa i t naiadrsme n b ecunoeeta f e lcgdnrie/ywgygwww w w wgwgwgwgy g g ygwgygwgw w w ywwgygwy", 86},
		{"gebuorid e c iceuttlrt s p uaectisna y l lroruhno/wwgygwyy y y wgygggygw w w wgwgggwgw w w wywgwgww", 85},
		{"nhruitvv l m orlcccyec r l seiuniset v e lseteeen/wwgygwyw w w wgygwgygy g g wgwgwgygw w w yywgwgwy", 84},
		{"euadmlnn m u lamtsnimi e d utenrfdlt e n pioaelye/ywgygyww w y wgwgwgwgw g g wgygwgwgy w w yywgygwy", 83},
		{"naiekoee h u sitspedtc h f rtiidertn c e nssgetnr/wwgygwyy w w wgwgggwgw w w ygwgggygw w y wywgygwy", 82},
		{"crsaeeby t t epnttesnn a r rexlarneo g e yurrnwsa/wygygyww y w wgwgggwgw w w ygwgggygw w w ywwgygyy", 81},
		{"uaittnps h n eirfnrrol l r nrnaeitgr e h tedeteur/ywgygwwy w y wgwgygwgw g g wgygygwgy w w ywwgygwy", 80},
		{"hpnenela p c asaittten a l giiherute u e cderelnb/yygygyyw w w wgwgggwgy w w wgygggwgw w w yyygwgwy", 79},
		{"iavslrid c d upertnpra o e slnngeetd a e giaaetri/ywgwgwyy w w wgygggwgy w y wgwgggwgy y w wywgwgyw", 78},
		{"eaowttne s m eentrekec d d uptayfdll c u xwltehli/ywgwgyyw y w ygwgggwgw w w wgwgggwgw y w wwwgygwy", 77},
		{"nrrteiid n r hrcgciigt a t wuiteitto o e siearncg/wygygwyw w w ygwgwgygy g g wgwgwgwgw w w wyygygww", 76},
		{"aelennki c c nrlostsro s n eioitaaev m a torgtete/yygwgwww w w ygwgggwgy w w ygwgggwgy w w ywwgygwy", 75},
		{"tnsiatod d i ecentaxnb r i eehitiagn t u ihdlngto/yygygyyy y w wgwgggwgw w w wgwgggwgw w w yyygwgyw", 74},
		{"aafuzvea a u tnnrnaaay e l nmemdomhi e t dienyslt/ywgygwyw y y ygygwgwgw g g wgwgwgygw w w ywwgygwy", 73},
		{"dmauevab h l etxreigey e s rteactndi t s reeebdol/wwgwgywy w w ygwgygwgw g g wgygwgwgw w w wywgygwy", 72},
		{"gnsdesdt n l csraitenn t r auaupulli i p sneastss/wygygyyw w w wgygwgwgw g g wgygwgwgy w w wyygygww", 71},
		{"notogeen f c ssiroanmo n c cecoeibnu l c aoefsrar/yygygwyw y w wgwgwgwgy g g wgwgwgwgw w w wyygwgww", 70},
		{"opealsae o m maeptirts e s cplrluret e e tagrlenr/wwgygyyy y w wgwgwgwgy g g wgwgwgwgw w y yyygygwy", 69},
		{"nsasante c m sueherddr a r etrrranet s l eseyiepf/ywgwgwyy w w ygygggwgy y y ygwgggwgw y w wywgwgww", 68},
		{"cacgihsa i h ncealkrei p w eantcersd c e rlrrhlcr/yygygywy w w wgwgygygy g g ygwgygygw w w ywwgwgyw", 67},
		{"artdamap n e iawprohee s e ntcothldv e k oerttroe/ywgwgwyw w y wgwgggwgy y w ygwgggwgw w w wyygwgwy", 66},
		{"bnoretpn y a artlyihgl t s eimquentc g u nrlentii/wwgygyyy w w wgwgggwgw w w wgwgggygw w w wyygwgwy", 65},
		{"rdodtuve e e gseeciela b e vmarriuya r d asrnllap/yygwgwwy w w wgwgggwgy w w wgwgggwgw y w yywgwgyw", 64},
		{"ecietdpd e n noptopasi c i dpartiioc o r lermpgun/ywgwgyyy y y wgwgggwgw w y ygwgggwgw w w wywgwgww", 63},
		{"nutxqnns n t cdrnaiute k n tooiiisni m a eunguepe/yygwgwwy y w ygwgwgwgw g g ygygwgwgw w w yyygwgwy", 62},
		{"negeapar e o rdiippdda f p elmterdlu r a teadrlte/ywgwgwww y w ygwgggwgy w y ygwgggwgy y y yywgygwy", 61},
		{"memlidnv r c ssbspeute i o naciatera e r dvneoaci/wygwgwyw w w wgwgggygy y w wgwgggwgy w y ywwgwgww", 60},
		{"uotsntid n x delpvadno p r senieeete a e ghlgetis/ywgwgyww y w ygygwgwgw g g wgygwgwgw w y wywgygyy", 59},
		{"ussputbi r e mftnrsper b t leduiasee t c yelnhetl/wwgygyyw y w wgwgwgwgw g g wgwgwgwgy w w yyygwgyw", 58},
		{"deoitnai e i oaamcnrcd o n bdtsraida s e iglsdeel/yygwgwyy w w wgygwgwgw g g wgwgygygw y w ywwgygww", 57},
		{"eifdstal i p apertislt e e senithvte m t ueuedrra/yygygwyw w w wgwgggwgw w y wgwgggwgw w y wywgygww", 56},
		{"ntcmiiee t d iscnspitd n i uaeryluco e d aabledoo/yygwgyyw y w ygwgggwgy w w wgwgggwgw y w wwwgygwy", 55},
		{"nagntieg f n alotertlt b a uahilieyu e e idrgngae/wwgwgyyy w y ygwgggwgw w w wgwgggwgw w w wywgygyy", 54},
		{"isulelel r n aiostaitt i p lfnittara g a nwegucln/wwgygyyy w w ygwgggwgw w w ygwgggwgy w w wwwgwgyw", 53},
		{"ariiroed t e ndpntueeg t e sldtrisen s k trdraeae/yygwgwyy w w wgwgggygw w w ygwgggwgw w w ywygygww", 52},
		{"omaeiuoo g s ksmarmire r e eismmrdlt g n lmndneag/yygwgwww w y wgygwgwgw g g ygwgygwgw w w wwygwgwy", 51},
		{"olttatse c t tpherinrs a m taisiaseg r m uarnoenr/wwgygyww w y ygwgygwgy g g ygwgwgygw y w wywgwgwy", 50},
		{"eeirtvdt e h mbtpollrw n s ninoniegs i i rreemgaa/ywgwgwyy w w wgwgggwgy w w ygygggwgy w y wyygygwy", 49},
		{"srpcolav t s lpuintorn s t ieramaoey g m grredeel/ywgwgyyw y w ygwgggwgw w w wgwgggwgw w w yywgwgwy", 48},
		{"teceiehp i n iaoricutu f s efuolilht o o recsdroa/ywgwgwww y w wgygggwgy w w ygwgggwgw w w wywgygwy", 47},
		{"feorueue e n voeepdfen r r rirslactx t d crpevtrr/yygygwwy y w wgwgwgwgw g g ygwgwgwgw w w yywgwgww", 46},
		{"eeidpdum r c edpploras o s icroleeto k m raseedle/ywgwgwww y y ygwgggwgy w w wgwgggwgw w w yywgygww", 45},
		{"uenrbeua o l dnrediegi e h yonficire l v ggolfese/yygwgwww w w wgwgggygy y y ygwgggwgy w w wywgwgyy", 44},
		// {"reispoen l r pdsvelnpg n e dittrueer o d lesdeeio/yygwgwyw w w wgwgggwgy y w ygwgggwgw w w wyygwgww", 43}, <-- Ambiguous
		{"riterrro t o nthancuer w n eicspineu l e lvrteepn/ywgwgwyy w w ygygggwgw w y wgwgggygy w y wwygygww", 42},
		{"enfdurla l o lnltabuei n a amslaraat a o nacyitiy/ywgygwyy y w wgygggwgy w w wgwgggygw y w yyygwgww", 41},
		{"tmreueud n n hiaflaiem i i rtmskiagt u e afrlemfn/yygygwwy w y ygwgggwgy w w ygwgggygw y w wwwgygww", 40},
		{"ielirdsg e m hrpbuiadn i u lnotrisea t i ihartgnl/ywgygwyw y w wgwgggwgw w y wgwgggwgy w w wyygygwy", 39},
		{"oiceloue m e amsntgaro t g gerokienn l d aifthgea/wwgygwww w w ygwgwgygw g g ygwgwgwgw w w wyygwgyy", 38},
		{"crnsenrm k i dadreavyc e c rpuodudtr o p ltssreue/ywgygwyy w w wgygggwgw y w wgwgggwgw w w wywgygww", 37},
		{"ecnuooce o q aaouftuci t s dsvrjiuec s s lnlnseii/wygwgyww y w wgwgwgwgy g g wgygwgwgy w w ywwgygww", 36},
		{"daoarult r e uoatomenr b g eesablnrw m s uusterpa/wygwgwww w y ygygggwgy w w ygwgggygy w w wyygygwy", 35},
		{"nsbpalco e a tslorrnnb a i hidstamlg a w aiemelsg/yygwgwyw w w ygwgggwgw w y wgwgggwgy w w ywygwgwy", 34},
		{"pmanieid s u dsleciasl e d iaetriper d t siedllar/yygwgwyy w w ygwgggwgw y w wgwgggwgy w y wyygwgwy", 33},
		{"ecsouona o e dfrleiega u f gcureirle d p urdendsh/yygwgwww w y wgwgwgwgw g g wgwgwgwgw w w yyygwgyy", 32},
		{"sleaiust h v dnoccesrt l r ainoealeh n s tmretefl/ywgwgwyw w w wgwgwgwgw g g ygwgwgygw y w yywgygwy", 31},
		{"mllnpoel y g yibpliade o e oaeettlrn e a raidsrrc/wwgwgyyw w w ygwgggwgy w y ygwgggwgy w y ywwgwgww", 30},
		{"uuodpmpo i o rfetneese e s lsoortrrt d l aeekhduu/ywgygwyw w w ygwgggwgy w w wgwgggwgw w y wywgwgyy", 29},
		{"atbgrner i g moierdado e l yisducare l o aenrvlml/ywgygwyw w w wgygggwgw y w ygwgggwgy y w wwwgwgyy", 28},
		{"adotpwet a b rahscocde n e dtpibueen r h rtrgceuh/wwgwgwyy w w ygwgggwgy y w ygwgggwgw w w wwygwgwy", 27},
		{"smeeavps r x dsclaoftc i c taeppauee r t elleaosn/ywgygwyw w w wgwgwgwgw g g wgygygwgw w w ywwgygwy", 26},
		{"mirtieib p n latgllece a n apsteeetu i e xdnalsrn/ywgygyyw w w wgwgwgygy g g wgwgwgwgw w w yywgygww", 25},
		{"besnrxat c v agerolral v i lntaeeyto c r eivtiese/yygwgwww w y wgwgygwgw g g ygygygwgy w w yywgwgww", 24},
		{"ucpmonop r l tatategru y r eipflasea l k nrulreyn/wygwgyyy w w wgwgggwgw g g wgwgggwgw y w yywgwgyw", 23},
		{"tcvcsrou o r dbpneares o i itsueiett e g coiehkar/ywgwgyyw w w wgwgwgwgw w w wgygwgwgw y w wywgygwy", 22},
		{"henreubq n i tmerluree e q aduuotado o d yieearnc/wwgygyww w w wgygwgwgw w y wgwgygwgy w w yyygwgwy", 21},
		{"thfeccun h t isistasni n i husitisgl g o ndigceiu/ywgygwww y w ygygggwgy y w ygwgggwgw w w wywgwgwy", 20},
		{"eiitoael g n pcrptujed u n yclnteetb a a oimertlc/ywgygyyy y y wgygggwgw w w wgwgggwgy w w wywgwgwy", 19},
		{"iiaiadme l s umtnsoanb o e mreskilre s e dndaehoa/ywgwgyyw w y ygwgggwgw w w wgygggwgw w w ywygygww", 18},
		{"rtoiamtg i n naredomel r r nsnaeivap n f dellhgen/ywgwgwyw w y ygwgwgygw g g wgygwgwgy w w wywgygww", 17},
		{"eemoenom g a tceiubmrl s r tnrtoasec c a iptnneto/ywgygwww w w ygygwgygw g g wgygwgwgy w w wwygygyw", 16},
		{"maoxeyvu o p sertvattv d s rerooicea r t yrnrtnbn/wwgwgwyw y w wgygwgwgw g g ygwgwgwgw w w yyygygww", 15},
		{"twsruldr l r ferumiied e l elngrosku e a abeevmrg/ywgygwyw y y wgwgwgwgy w w ygwgygwgy w w ywygwgyw", 14},
		{"asiipeon l m saecetrcs n e gdrsmiase m i noaritda/yygwgywy w w wgwgggwgw y w wgwgggwgw w w ywygwgyy", 13},
		{"nesrfaut e g ssaahitne p l ndtpmuael u i oolrbeer/wwgwgyyw y w wgwgwgygy g g ygwgygwgw w w wywgwgwy", 12},
		{"pnrbevvt n g tldmbiegc e o ienasiaec u i lvetanxo/wygygwww y w ygwgggwgw w y wgwgggwgw w w yyygwgyw", 11},
		{"autasedr n i onfrrafap d y eooieiynn i v senrpgoa/ywgwgwyy w w wgwgwgwgw g g ygygwgwgw w w wywgwgyy", 10},
		{"ceninrai t c uaatretsa c e stfrmines p i uaelired/yygygwyy w w wgwgggwgw w y ygwgggwgw w w wwwgygww", 9},
		{"hiawtcsn u o irydaaete r c esteltdeo d i srrsarpl/yygwgyyw w y wgwgygwgy g g wgwgwgwgw y w wwwgwgwy", 8},
		{"inmoacrm e e iaigolncc h e dstaeerdw s e lemeitna/yygygyyw w w wgygwgygy w w ygwgygwgw w w wywgwgwy", 7},
		{"cespnbsa n e saeoatdds a n irilrapem l e nstdgeee/yygwgyyy w w ygygwgygw w w wgwgwgwgy w w yywgwgwy", 6},
		{"muinoeum c m siaputtsn r c naneiorec t s mrdscesw/wygygwww w y wgwgygwgy g g ygwgwgwgw w w wyygygyw", 5},
		{"ruorglcu p u gorttaaen h t rsephouto t r uetsearh/yygwgwwy w w wgygwgwgw w w ygwgwgygw w y wyygygyy", 4},
		{"dsvsosgu r e rmdbrtors t c issaiines u b oyieueoe/wygwgwyw y w ygwgwgygy y w wgygwgwgy w w wywgwgww", 3},
		{"abnserou i l ialmeeist f b rarryaseu m y sellsdam/yygygwww w y wgygwgygw w w ygygwgwgw w w wyygygwy", 2},
		{"taenergt r e perpsersd m x iaretaler m n vscsrevd/ywgygyww y w wgygygwgy w w ygygwgwgy w w wwwgygwy", 1},
	}
	dailyWaffles = []TestCase{
		{"ftlrha n asnille a olkuoy/gwywgy g wwwgwgy w ygyywg", 919},
		{"iuenti e uidsrto h stsshe/gwywgw w wywgwyw w wgyyyg", 918},
		{"fanoyo i rcrtrhl i bapart/ggywgy y wywgwyy w wgwwgg", 917},
		{"petayo k pesrusa p elaart/gwwwgw y wywgwyy y ygwgwg", 916},
		{"tleahl c lenocor n teafmy/gwyygw w ywwgwyy g ygwwgg", 915},
		{"atrtou d sutaoaf e iceitr/gwywgw y wwygyww w wgywyg", 914},
		{"rlsahe a iecpeem d erivey/gwwygy y wywgwyw w wgwwyg", 913},
		{"bnelda m sukadel e sniggy/gyyygy g ywwgwww w wgwywg", 912},
		{"soenkt m reedule u npcitl/gyywgg w wywggww w ygwywg", 911},
		{"naaaro v eeaucta b clncsh/gwywgw y wwygywg w ggwywg", 910},
		{"sanoaf e ahdfoul u ltaony/ggywgw y wywgyww y ygyywg", 909},
		{"aaitdg l wlebalr m oniaul/gwywgg w gyygyyw w wgwywg", 908},
		{"dbrani r dhwogua t vliuae/gwyygw w ywwgwyy y wgwyyg", 907},
		{"inrreo u trnieol r ptoaer/gwywgw w wywgwyw w wgyyyg", 906},
		{"tvopls r milapri o yclirt/gwgwgw y ywygywg w wgwwyg", 905},
		{"cnsuno e olimaut o lhtkdy/gwwwgw g wyygyyw g wgwywg", 904},
		{"adtpni e lognais a oecrmh/ggwwgg w wwwgywy y ygywwg", 903},
		{"laetdc a cetllio k ihoiph/gwwwgy y yyygyyw g wgwwwg", 902},
		{"untcde l ewpiher s mrreoy/ggywgy w ywygwww g wgyywg", 901},
		{"gahcno e miagoca n trrrih/gwwwgw w wywgwyy y ygwywg", 900},
		{"tlmngt a wehogum i nadnje/gwyggy y wgwgwyw w wgwywg", 899},
		{"hcceer a ouewrta l nherey/gywygw w wyygyyw w wgwgwg", 898},
		{"clickb u umhiunr a hcpaet/gwwggy y yywgwww w wgwyyg", 897},
		{"sliatm g fteaeir p hfarld/gywygw g wywgwyw g wgwywg", 896},
		{"cawodn e rhnteoy s rsrefr/gwyygw y gyggyww w wgwwwg", 895},
		{"lerinu s eyvsito n armehe/gywygw w wwygyww y wgywyg", 894},
		{"poragr f eoneala t dlmegy/gyywgw w wwwggyg w ygwywg", 893},
		{"puslek l eoeditv m atnroe/gywygw w wywgwyy w ygwgwg", 892},
		{"mvaore n ispiiuk m wcelhy/gwyggw y wgygwww w wgywyg", 891},
		{"cvrgbe p muiprue r aeuide/gwywgw g wyygyyw w wgwywg", 890},
		{"geehnu e urrgaer n etrvae/gygwgw y wywgyyw w wgywwg", 889},
		{"ideirr u ennbnim a cteeur/gwwwgy w yywgwyw y wgywyg", 888},
		{"riised e epaelee f itwxll/ggywgw w yywgwyg y wgwwwg", 887},
		{"stamea a glmoeni w yprlne/gywygy w yywgwyw w wgwwwg", 886},
		{"kdepal f ueaodbh l kiaont/gwwwgw g wyyggyy y wgwwyg", 885},
		{"llrmha n rmobnau d aaaegy/gwywgy y yywgwyw w wgwwwg", 884},
		{"hnroyt a esarwuc m dymaay/gwywgy y wgygwyw w wgwywg", 883},
		{"aluieh o oldapnr g lailrw/gwywgy w yyygyyw y wgwgwg", 882},
		{"pgroeo a llisnba o ttnasy/gwywgy y wgwgwyw g wgyywg", 881},
		{"muooet a bgyuerh n aleagr/gwywgw w wywgwyw g wgyyyg", 880},
		{"sdaakl e hrcileb a npkllt/gwgwgw y wywgygw w ygwywg", 879},
		{"otearw d craafie f tttrry/gwywgw y wywgwyg y ggwywg", 878},
		{"bacnhi e cevroei l awvrue/gwywgw g wyygwyw w ygwywg", 877},
		{"meroya l ureiter d aroodl/gwywgw w wyygyyw y wgwwwg", 876},
		{"stciki o hatglit a idltny/gwyygw y wyygyyw w wgwgwg", 875},
		{"cnbrke i vulilnr l adolnl/gyyygw y wywgwyw y wgwywg", 874},
		{"vedngl i ysoliia v utrohm/gwyggw y wgygwww w wgywyg", 873},
		{"ceuuls m rsiagit s eewnae/gwwwgw g wywgwyy g ygwywg", 872},
		{"vudiat c lnsarua e uegivt/gwwygw g wwwggyy y wgwwyg", 871},
		{"saetda w tttanok t spoiry/gyyygy g yywgwyw w wgwywg", 870},
		{"sttcbe u oirvoie r ctrurh/gwwygw w wyygwyw y wgywwg", 869},
		{"mriacp a haoiscz i ewrmhe/gwywgw g wywgwyw w wgyyyg", 868},
		{"crxehs l ourbnam o etioen/ggywgw w ywygwww g ygyywg", 867},
		{"epnler g nutiebc g wroley/gyyygw y wwygyww w wgwwwg", 866},
		{"serrda l speirae i rghagd/gwwggw y wyygyyw w ygwywg", 865},
		{"sfntft e dptieew i utnecd/gyyygw w wyygyyw w wgwgwg", 864},
		{"vuerma t anoduce l neaaih/gwywgg w wywgwyw w yggywg", 863},
		//{"rzteeo c lroaxgs e uegrut/gwywgg w gywgwyw y wgwywg", 862},
		{"ypoeht i lolsieu t adeeex/gwywgw w ywygwyw y wggywg", 861},
		{"rtceht a ietoflo u uterar/gyyygw w wyygyyw g wgwywg", 860},
		{"clathc p mhnuhpo c daroay/gwyygy y wyygwwg w ggwwwg", 859},
		{"snfufp o hautdee d nrecey/gwywgw y wywgwyg y ggwwwg", 858},
		{"teoaos r hewaedr y wlstar/gwywgw y ywggwwy y wgwwyg", 857},
		{"wrrehs e thikcer o dfwaay/gwywgw y wywgwyg w ggwywg", 856},
		{"bphoet r maaastp i msatiy/gwywgw y gywgyyw y wgyywg", 855},
		{"raoyon a teccaoo e drioen/gwywgw w wyygyyw y wgwywg", 854},
		{"peicnm e reabiry g iducee/ggwygw y wywgyww w ygwywg", 853},
		{"jsoutc e oarcvmr l bonhut/gyyygw y wywgwyw g wgwwwg", 852},
		{"cniels m uhaomde a opcgre/gwwggw y gyygwyw w wgywwg", 851},
		{"dsrloe n pedkaeg e ieddar/gwwwgw y wyygyyw g wgwgwg", 850},
		{"basptd e lnntryl j recuit/gwwwgy y wwwgwgy w ygyywg", 849},
		{"alfatu e heodugi r nloair/gwywgg y gywgwyw w wgwywg", 848},
		{"brhudm b vylbsee a etnere/ggwwgw g ywygwyw y wgwywg", 847},
		{"imweep e oiraepa x rlnnny/gwywgy y yywgwyw w wgwwwg", 846},
		{"ravgli a ieaoenr e etlpet/gywygg y wyygwww w ygwwgg", 845},
		{"dkrsdi o rntnuic i ayeiey/gwywgy g yywgwyw g wgwywg", 844},
		{"thmgbo i ortaeei l nreaan/ggywgw w ywygwwy g wgyywg", 843},
		{"mimofe o halutgc d aaoybr/gywygw g wywgwyw w wgywyg", 842},
		{"cuskms n mraismr e veahvy/gwywgw g wyyggyw y wgwwyg", 841},
		{"ssaofr i roitcar n fpette/gwwwgy y yywgwyw y wgwwwg", 840},
		{"tirnnt g eaihthi e chsiee/gyywgy w wwygyyw g ygwywg", 839},
		{"cyrsde l vkaortr i asrmre/gwywgw w wwygywy y ygwwwg", 838},
		{"fluine t rnevron e ahoroy/gywwgw w wyygyww g ygwgwg", 837},
		{"dnauki n nrxcrea t reucma/gywygw g wywgwyy y ygwwwg", 836},
		{"ainhnh g sbiiniu l cegsgt/gyywgw y wywggyy w wgywwg", 835},
		{"daaeaz m zlbarpm e otacwk/gwgwgw g wywgwyw y wgywyg", 834},
		{"vworlo a yeracep m areail/gyywgw w wwggyyw w ygwywg", 833},
		{"qlreal p aueeudt o atriey/gwywgw g wywgwyw y wgywyg", 832},
		{"fnoana w xroivoa r lkmned/gwgwgy w wyygwyw w wgwyyg", 831},
		{"fxupse l sominer p ltdpot/gwywgw w wgwgwgy y ygwywg", 830},
		{"flsihi o ecanero z oontge/gwwwgy y wwwgggy w ygyywg", 829},
		{"mtstee a iatutno d togerr/gwwwgw g wwygywy y ygwywg", 828},
		{"dpgdeo c eeosldr t gaoeit/gwyygw y yyggyww w ygywwg", 827},
		{"drkema u iieuroo e gtltcn/gwywgw w wyygyyw w wgwywg", 826},
		{"taepym k iaarura s oraetn/ggywgw w wyggwyw y wgywwg", 825},
		{"orlyne d alcipte o acailn/gwywgw y wywgwyw w wgywyg", 824},
		{"traopm e wnedeiu i rlidyc/ggwwgw y wywggyw w wgyyyg", 823},
		{"csrccm n lehbhoo r eesoit/gwwwgw y wywgwyy w ygwywg", 822},
		{"tagutr p ihnuals l itmsay/ggwygw w gywgwww y wgwyyg", 821},
		{"tteake t eoelunl i nmnrul/gwwwgy y yyygyyw g wgwwwg", 820},
		{"soxltl n rienpuu e hepcwe/gwwwgg g ywygwyw y ygwwwg", 819},
		{"fdjedv a airocho o itbrey/gwywgw w wyygyyw y wgwwwg", 818},
		{"mgguli e larioda r ocpdve/gwwwgy y wywgwgw y ygyywg", 817},
		{"bglddu t oneuaol r ttnxny/gwywgg y gywgwyw w wgwywg", 816},
		{"edgael o intetla f enavxl/gyyygg w wwygwyw w wggwwg", 815},
		{"stornd r fdefnoi e etpany/gwgwgw y wwygywy g ygwywg", 814},
		{"ecoile n txlleoo g osshoe/gyywgw y wwygygg w ygwwwg", 813},
		{"surkep h rrotnik o vtdove/gwwwgw w wyygyyy y ygwgwg", 812},
		{"blkoea e tutstoe c nhrmny/gwyygw y wyyggww w ygwwwg", 811},
		{"vrioor e oamedec e klaaan/gwywgw w wywgwyy w ygwywg", 810},
		{"dctuhr e arrgoan l ulecnh/gwywgg y wwggyyw w ygwywg", 809},
		{"tmbhbn i siysoue t uaeelr/gywygw w wyygyyw y wgyyyg", 808},
		{"aoromt a pralomu i enbldh/gwywgw g yyygyyw w wgwwwg", 807},
		{"reiltn d maoidne h ooolbr/gwwwgy y ywygyww w wgwywg", 806},
		{"kfpnla o nbeieul s lbtesy/gwyygy y wgwgwyw w wgwgwg", 805},
		{"bispna r ygmapwu a slcanh/gwwwgg w gwygyww y wgywyg", 804},
		{"gieare r gvnrefp s otmhae/ggywgw w ywygwww g wgyywg", 803},
		{"mtniri d ielarew s oaeayc/gwwwgy w yyygyyw g wgwwwg", 802},
		{"lmchhe r eeytmer u oredne/gwywgg y wywgyyw w ygwwwg", 801},
		{"deoipe i amrbtlr f rtoarn/gwgwgw y wywgwyy w ygwywg", 800},
		{"lcixtu i iaantmc h aeiiat/gwywgw w yywgyww w ygwwyg", 799},
		{"boerdf o uletool s nhinly/gyyygw y wywgwyw w wgwgwg", 798},
		{"tecakh h naaeerh r ywdank/gwwygg w wwwgyyw y ygwgwg", 797},
		{"cjefea l smlohte t itrnle/gwywgw g wywgwyy w ygwywg", 796},
		{"reeboy i ecestuo t rdacrr/ggywgw w wywgwyy g wgwwyg", 795},
		{"rralth l gnteigi c iteave/gwgwgy w yywgwyy w ygwwwg", 794},
		{"hevphd o efdoity a adrety/ggywgw w gywgwyy y wgwwwg", 793},
		{"faanlo e vluvgii o rsecae/gyyygw y wwwgwwy w ygwwwg", 792},
		{"vanttn c akeioei u ilraln/ggywgw w gywgwyy y wgwwwg", 791},
		{"rcueya o cllbeac i upkala/gwwwgy w ywwgwwy w ygyyyg", 790},
		{"wirdrl s tslooki d ohriey/ggyygw w wywgwyy y wgwwwg", 789},
		{"shuoen t uampral i wmeitl/gwywgw y wgwgwgw y wgywyg", 788},
		{"bcouht t reattlr r pnaaiy/gwgwgw y ywygwyy w ggwwwg", 787},
		{"woeedu e rthguca l opichh/gwgwgw y wyygyyw w wgwywg", 786},
		{"hihaye r rdlaseo p wdwopl/ggywgw w wywgwyy y wggwwg", 785},
		{"esenli e ttpsoee a kgnsxe/gwywgy w yywgwyw w wgwywg", 784},
		{"botcno e icrmenr t shuaah/gyywgw g wwwggyy w wgwywg", 783},
		{"vimade e mllaapu p ersiry/gywygy g yywgwyw y wgwwwg", 782},
		{"baesye e owdnsni d enialy/ggywgw g wywgyyy y wgwwwg", 781},
		{"bnvehe e slcvsar n atleie/gywygw g wywgwyw y wgwywg", 780},
		{"celrhe s oasgeca v nnuuue/gwywgy w wywgyyw w yggywg", 779},
		{"cecekt t ettainr v iporcy/gwywgw y wywgwyy y ygwwwg", 778},
		{"ceegkr m rlorare e npeill/gygwgw w wywgyww w yggywg", 777},
		{"goulme a mtmiukr o uysdry/gyyygw w wywgwyw y wgwywg", 776},
		{"crenke s veuumnp a ithoed/gwwggy g wywgyyw w wgwwyg", 775},
		{"sekmlo c atpeiml i gpstnh/gwywgy w yywgwyw y wgwgwg", 774},
		{"baanee v uenisno r psavgt/ggywgw w wyygwyy y wgwwwg", 773},
		{"sitgla w aopresu d anctle/gwywgy w yywgwyw y wgwwwg", 772},
		{"blefez e raeagir t mtewxt/ggywgw w ywygwww g wgyywg", 771},
		{"strooe n exuiyse l hfvear/gwgwgy y yywgwyw w wgwywg", 770},
		{"clveno e ceetuwu t dhgroe/ggwwgg y wywgywy w wgywwg", 769},
		{"ptlelu r eaebuii t aytlad/gyyygw w wyygyyw y wgwywg", 768},
		{"swnipm n tativfd a ofcaoy/ggywgw w ywygwww g ygyywg", 767},
		{"sednkt c cuduell l aeeclt/gwwwgw g wyygyyw w wgyyyg", 766},
		{"qulaew o lteboeu e ombnur/ggywgw y wywggyy y wgwwwg", 765},
		{"bemeos e theuwpa e strnvd/gwywgy y yywgwyw w wgwwwg", 764},
		{"wofihi t aeggetn c irhceh/gwwygw y wywgwgw w ygwyyg", 763},
		{"mkoila r oidpdoc a ortuuy/gwywgw y wywgwyw y wgwywg", 762},
		{"bapgeh a utsarel m slsane/ggywgw w ywygwww g ygyywg", 761},
		{"senaad l ahcigxa u lerlby/gwywgy w yywgwyy y ygwywg", 760},
		{"bslobr o rtzhteu r teeeah/gwywgw w yywgwyw y ggwyyg", 759},
		{"darlsr m aeobulc e erpesl/gwywgw g wywgwyy g ygwywg", 758},
		{"skprlt e eneseah u ediulr/ggywgw y wywggyy y wgwwwg", 757},
		{"fubrti r naibrca o umgwae/gywygw g wyygyyw w wgywyg", 756},
		{"bglrne l dinagld n aeaeur/gywwgw g ywygyww g ygwywg", 755},
		{"gneymo o rledreo h ttsrrh/gwywgy y ywygyww w wgwwwg", 754},
		{"sepuee o ranpler l pdeaey/gyywgw w ywwgwyw y wggywg", 753},
		{"cyiiov g lrlivnl l emahet/gwwwgw y wwgggwy y ygwywg", 752},
		{"ceihma n adpouae s rtllrt/gywwgy w wywggyw w wgwyyg", 751},
		{"benids i nwlaiat l tdgiao/gwywgy y ywgggww w wgwywg", 750},
		{"tnhona r nbciior c elaune/gwyygy w wgwgwww w yggwyg", 749},
		{"lgteee i lvpseii o ddaere/gywygw w wwygywg w ggwywg", 748},
		{"snaoer e nirieev r vlsrty/gwwygw y wyggwgw w ygwywg", 747},
		{"loesde l oiaiekr t wrlrex/gwywgy y ywwgwww w wgyyyg", 746},
		{"srvdej i lgeohil b stycrt/gwyggw y wgygwww w wgywyg", 745},
		{"syurpa i neelkuu y epmare/gwwwgw y wywgwyg y ggwywg", 744},
		{"aerntu b uiliwhu o feghgt/gwwwgw w wwygwyg y ggyywg", 743},
		{"cnnafe i nllnlir l uglfiy/gwywgw y wywgwyw w wgywyg", 742},
		{"sasshv s itsaaal t iewlmy/gyyggw y gywgyww w wgwwwg", 741},
		{"salcla e edyieaw e tlftvr/gwywgy y yyygyyw w wgwgwg", 740},
		{"pature l rytcamn h upteey/ggywgw w ywygwww g wgyywg", 739},
		{"riceai i eugnifl a urgbmn/gwywgw y wyygyyw y wgwwwg", 738},
		{"bpcoha j eaansnr i asudiy/gwywgg y wwggyww y ygwwwg", 737},
		{"seoalu c cetfrat o lbihfh/gwgwgy w yyygyyw w wgwwwg", 736},
		{"baartu o lmsdera i heisue/gwyygw w wywgwwy w ygywwg", 735},
		{"vdiedt l aisltav i proiiy/gwywgw y wyygyyw w wgwwwg", 734},
		{"pkaanb k lnwarew n atcerd/gwgwgw y wywgwyw w ygwgyg", 733},
		{"hisehe e eetmtaa r nlpoar/gwywgy y yyygyyw y wgwwwg", 732},
		{"toebht c okeacea r uolicr/ggywgw y wywggyy y wgwwwg", 731},
		{"ssgalu u iosinlo p phmiun/gwwwgy y ywgggww y wgywyg", 730},
		{"satcnn e ribotnl e ittavh/gyywgy y wwwgwgy w ygyywg", 729},
		{"frewee l uugnaoo g rteout/gwywgw w wywgwyy y ygwywg", 728},
		{"scdapr e mrsdest o apiuoe/ggywgw y wywggyy y wgwwwg", 727},
		{"lhardc o iitceuu a scyoum/gwywgw g wyygyyw w wgwywg", 726},
		{"cuhecn l erebmni i ifooed/gwwwgw y ywygywy w wgwyyg", 725},
		{"caoasi e osottra r mcneut/gwwwgy y ywgggww y wgwywg", 724},
		{"edgatc r piiicsl n belare/ggywgw w yywgwww g wgyywg", 723},
		{"snlado l cpaeocd c vepare/gwywgy w yyygyyw w wgwgwg", 722},
		{"trrrln h etcgach o iwialh/ggywgw w wywgwyy y wggywg", 721},
		{"fespas e tllsoll o thnray/gwwwgy y yywgwyw y wgwwwg", 720},
		{"quailn r loktepu e alnoly/ggywgw w wywgwyy g wgywwg", 719},
		{"ieotoo t getatso o lrenpr/gwywgw y wyygyyw w wgwwwg", 718},
		{"llikne l enseuai g ttshay/gwyygw y wwygyyy w ggwwyg", 717},
		{"brnhdu n eerdruu u dtanom/gwywgy w yywgwyw y wgwwwg", 716},
		{"hoabre a gvdoiir l atseie/ggywgw w ywygwyw g wgyywg", 715},
		{"snagwc o henirlr h hpehle/gwwwgg y gywgwyw y wgwywg", 714},
		{"coosrh c ndekaaw e ohieoy/gwgwgw w wwygyww g ygwyyg", 713},
		{"tteulr u oaegrwe l cmncih/gwywgw w wwygywg y ggwywg", 712},
		{"fuutrl i oeuraat l udsily/gwywgw w wyygwwy y ygwwgg", 711},
		{"dskuye c eiweruu p olkews/gyyygy w ywygyww y wgwywg", 710},
		{"gruese u siancnu o wtntsk/ggwwgy g wywgwyy y wgwwwg", 709},
		{"llamrg e caeerag n pleyah/gwywgy w yyygyyw w wgwywg", 708},
		{"tnnoar m zkaaigw e ngaiey/gwwwgw g wwyggyy y ygwwyg", 707},
		{"aroame t rcuoral e nrdatl/gywygw w wyygyyw w wgwywg", 706},
		{"mioynu t wlsacor r esauin/gwywgg g wywgyyw y wgwwyg", 705},
		{"brcodd o iuornta g ahpdey/gywygw y wywgwyw w wgwywg", 704},
		{"lmihti r uiyrvms e aritee/gyywgg y wywgyww y ygwwwg", 703},
		{"kkehis u asaiebl s ibglne/gyyygw w wywgwyw w wgyyyg", 702},
		{"ggsipm d sreiaas s asrtse/gwywgw y yywgyyg w wgwwwg", 701},
		{"smeite h dtoiiae l ttlewr/gwgwgw w wyygyyw y wgwgwg", 700},
		{"eonits l ytrenah x rcaiat/gwywgw w wywgggy w ygywwg", 699},
		{"fremtp e ceaatsl t aemany/gwywgw g wwygywy w ygywyg", 698},
		{"ardatp e ntiomhl e btjrre/gwyygw y wwygywy w ggwwgg", 697},
		{"pcthsa r teeasri x emserr/gwywgw w wywgwyy y ygwywg", 696},
		{"ccrykc s uepalgr u aecmht/gywwgy g ywygwww y ygywwg", 695},
		{"pnuael t mlzpoir h teaxil/gwywgg y gywgwyw w wgwywg", 694},
		{"drlall r gidedfh a atluee/ggywgw w ywygwww g wgyywg", 693},
		{"nrbnlv a oatsail i eyaien/gwwwgw y wywgwyg y ggywyg", 692},
		{"sblelx a rprteaa e edhkly/gwywgw y wyygygw w ygwwwg", 691},
		{"ttoepo x aritaap c rretoy/gwgwgw w wwygywy y ygwgwg", 690},
		{"cahtnt w iyughon r uctity/gwywgw w wywggwy w ygywgg", 689},
		{"leleeh g ungidag y aeentr/gwwwgw y wyygyyw w wgyyyg", 688},
		{"hienyi u omtsric k udatuy/gyywgy w wgwgwyw w ygwgwg", 687},
		{"ldtano s aealrva t uosese/gywygw w wwygywy g ygwywg", 686},
		{"rodati e eaetfsv o ntgroy/ggwwgg y wwygwwy y wgywwg", 685},
		{"daexlr e mwliroi d wflpuy/gwgwgy y yywgwyw g wgwwwg", 684},
		{"fsnnkp a rdoixax l eseeld/gwwwgw w wyygyyw g ygwgwg", 683},
		{"nlowyr u tpsamsh a alefmy/gywygw w wyygyyw w wgwgwg", 682},
		{"rsnpeo e tseuqra i urrsay/gywwgw w ygwgyyw w wgwygg", 681},
		{"fctnen v rmxilvu n eeaeet/gywygw y wywgwyy y ygwgwg", 680},
		{"cgatla h aoaoioa a ynnbsl/gwywgy w ywygwyw w ygwywg", 679},
		{"roeite e seepksc s wyaoet/gwywgw g wywgwyy y ygywyg", 678},
		{"ttmuep u rpmicmo d mtariy/gwywgw y wyygyyw y wgwwwg", 677},
		{"uionni l hnnltih c iteiae/gyyygy w yywgwyw w wgwywg", 676},
		{"arioyp d ddeipea l utirel/gwwwgw y ygygwyw w wggywg", 675},
		{"ksuikt m raotucp o tyicia/gywygy w ywygyww y wgwgwg", 674},
		{"srrumn u etrgaar s ehwcuy/gyywgw g gyygyww w wgwwyg", 673},
		{"pbcrea o eliiudd d mazlbt/gywygy y yywgwyw y wgwwwg", 672},
		{"betamp s celeonc l krotah/gwwwgw y yyygwyw g wgwgwg", 671},
		{"smttdl a anuulic l aptsey/gwywgg y gwygyww w wgywyg", 670},
		{"roefhg i kunirle n gegluy/ggywgw w ywygwww g wgyywg", 669},
		{"dreeru i oeovoel n emonen/gwywgw w wywgwyw y wgywyg", 668},
		{"meatrn v eoouire t aftdcy/gyywgw y gywgwyw y wgywwg", 667},
		{"senogv u vredigd e lniune/gwywgy y ywygyww w wgwywg", 666},
		{"adleto e loruhel m htssve/gwyygy y wywgwgy w ygwwwg", 665},
		{"mdrmod h lobuoie a rldbty/gwywgy g yywgwyw w wgwgwg", 664},
		{"liuose t asccamo a trhure/gwyygg y ywwgyyw y ygwwwg", 663},
		{"smdiyo w gnalwld e enarpy/gyyygw w wwygyww g wgwgwg", 662},
		{"eoiaya l nchnioe y lsevtd/gyywgw y wyygwww g ggwywg", 661},
		{"wirato a oeeiigs s nrdtco/gywygw w wywgwyy w ygwgwg", 660},
		{"lrnsns o auessra i eriohe/gyywgy y wywgywy w wggwwg", 659},
		{"odrlne u dtrieei w tdecey/gyyygy w ygwgwgw w wgwwwg", 658},
		{"breihn e hntboro m utrtna/ggywgy w wywgyyw y wgwywg", 657},
		{"sckeep p eurcaxg l oekuoy/gwywgw w wywgwyy w ygwywg", 656},
		{"sornfp m gceigke r nlaley/gwywgg y ywygyyy w wgwwyg", 655},
		{"rietpd t eenmdao o aweacy/gwywgw y wyygyyw y wgwwwg", 654},
		{"akbotn a exnilab t stiegn/gwwwgw w ywygyyy y wggywg", 653},
		{"cekuei e eohtapa c hcbdjt/gwywgy y ywygyww w wgwgwg", 652},
		{"sklare t kisydfb l sfloiy/ggywgw w ywygwww g ygyywg", 651},
		{"tuarpm x ninbroi n hpueme/gywygy y ywygyww y wgwwwg", 650},
		{"slarll g tmtreoa e vloare/gygwgy w wywgyyw w wgwgwg", 649},
		{"slaehi e acaorsk w invwme/gwgwgy y ywygyww y wgwwwg", 648},
		{"pogphc a godiwel n eruoee/ggywgw w ywygwyw g wgyywg", 647},
		{"svrblc e tsthiua o nenaah/gwywgw w wywgwyy g ygwywg", 646},
		{"tvwuts a rurflin t csloie/gwywgy y wgwgwyw w wgyywg", 645},
		{"lnnyge s ustaime s reavny/gyyygg w gywgwyw w wgwywg", 644},
		{"awdetp e iebrhht t bcoiuy/gwyygw g wwygywy w ggwywg", 643},
		{"psaohc r boebsar d feeiry/gwywgw y wyygyyw w wgwgwg", 642},
		{"flrohs r durdnsl e etehoe/ggywgy w ywygwww g wgyywg", 641},
		{"calose e lhlpmih x ameesr/gwywgw y wwygyww y wgwywg", 640},
		{"praiel i rirbste e oldaer/ggwwgw y wyygwwy w wgwygg", 639},
		{"sloane n eetmunt o ntchoh/gyyygw y wyygyyw g wgwwwg", 638},
		{"acdgnr n nonovsr i itdeay/ggywgw w ywygwww g wgyywg", 637},
		{"csalke l keeival l npraod/gwywgw g wywgwyy w ygwywg", 636},
		{"gswoni e errdaor p ehrvde/gwyygw y gywgyww w wgywwg", 635},
		{"mlakll m eobaule o mraraa/gwywgw y wywgwyg w ggwywg", 634},
		{"coatrr f eyafeaa w uraoel/ggywgw w wyggwyy y wgywwg", 633},
		{"sayalo c etcaerv t rpwate/gwywgw w wyygyyw w wgwywg", 632},
		{"sehdtn e uaaooeb l tknprl/gyywgy y wgwgwww w yggwwg", 631},
		{"cuelna d oieveiv n aroair/gwywgw w wywgwyy y ygwywg", 630},
		{"oewear g rrlaced m nrlety/gywwgg w wyygwyy w wgwyyg", 629},
		{"sfvdta r pieaehe c rtghnt/gwwwgw g wwygywy g ygwywg", 628},
		{"sorsgg n nwoteii u ngonre/gwywgw g wyygwyy w wggwyg", 627},
		{"rnisrr h mnsoeaa c gtoeid/gwwwgw g wywgwyy y ygwgwg", 626},
		{"bespeo j ureniin i rseale/ggwwgg w wwwgywy y ygywwg", 625},
		{"heisyi y cosnraw h dtoidt/gwywgy y yywgwyw w wgwwwg", 624},
		{"eebohe t mecsotn o areepr/gwwygy y wywgwgw y ygwywg", 623},
		{"feighg c aonoliw s tloile/gwywgw w wyygyyw g wgwywg", 622},
		{"vealeu a teiaefl y edsarr/gwyygw w yywgwwy y ggwwyg", 621},
		{"tnoens a ceiilob o rhnhoy/gwgwgw w wyygyyw g wgywyg", 620},
		{"soalth a ngaegcn a irugue/gywwgw w ygygwww g ygwywg", 619},
		{"bnathp c etotree r imoeay/gwywgw w wyygyyw w wgwywg", 618},
		{"grfief m euanuia m aaasel/gwgwgw w ywwggyy w ygywwg", 617},
		{"lgnsha o iiemrar a tnuech/gwywgw w wyygyyw y wgwywg", 616},
		{"sontew o tnreveo t impnrr/gwywgw w ywygyyy y wgwwwg", 615},
		{"terogn n niolnyh i ocigue/gwwwgy w yyygyyw y wgwywg", 614},
		{"trwlht p ittailu a epeosy/ggywgw w wywgwyy y wggwwg", 613},
		{"wccagt u iaeslpn t yhnnrh/gwwwgw y wywgwyy y ygwywg", 612},
		{"aicade i ubrneoo v wterrd/gywwgw w wywgyyy w wgygwg", 611},
		{"snmlgs r oembene i oculie/gyyygw w wywgwyw y wgwwwg", 610},
		{"ciiaci h enmoflv a npdllt/ggywgw w yywgwyw y wgwywg", 609},
		{"nieehc l nolvaar d eroety/gwywgy y yywgwyw w wgwywg", 608},
		{"clnupu e ielcmrs g udrire/ggwygw y wywgwgw w ygyywg", 607},
		{"vdedta a iitppiu l irteiy/gwywgw w wyygyyw y wgwwwg", 606},
		{"shuigr r agiduew e rkontl/ggywgy y wwygyww y ygwywg", 605},
		{"finenl r ydeitop o ntmpwh/gwywgg w gywgwyw y wgwywg", 604},
		{"uprcre m ubeizen p wtloed/ggywgw w wywgwyy y wgwwgg", 603},
		{"ccraea i sgsimln n hesume/gwywgy y ywygyww g wgwwwg", 602},
		{"allare w atlnosn a uhloey/ggywgw w ywygwww g wgyywg", 601},
		{"rnnudr t myeivoi h lrldee/gyyygw y wwwgwwy w ygwwwg", 600},
		{"vbsmtt e itiyhea a ralaod/gwwygy y wywgwgw y ygwywg", 599},
		{"sohcnk t eottute e rlaxey/gwywgw w wgwgwgw y wgyyyg", 598},
		{"mdluci o piamiye r ocnmby/gwwwgy y wwwgwgy w ygyywg", 597},
		{"kemaln e ragakil r ibfbey/gwywgw y wywgwyw w wgywyg", 596},
		{"lbgeha e aurdrur e adaddy/gwywgw w gyygywy g wgwywg", 595},
		{"boqndr e apsutat p astiiy/gwywgw y wwygyww y wgwywg", 594},
		{"prneer u aisnetl i etnlce/ggywgw w wywgyyy y wgwwwg", 593},
		{"svhoep p leetrsn f utoode/gyyygg w gwwgwww y wgwywg", 592},
		{"exlglo i etmorhl l otoaun/ggywgw w ywygwww g wgyywg", 591},
		{"coelhd a htlixol e asxdiy/gyyygw w wwygyww w wgwywg", 590},
		{"gterma s adcarae a lpwxel/gwgwgy w yywggyw w wgwyyg", 589},
		{"ptuiee m lmutenr r nblemy/gwgwgw w wyygyyw y wgwywg", 588},
		{"ianreg t innaiag r gttony/gyyygy w wywgyww w wgwwyg", 587},
		{"raebts r uesilts l ltewey/gwywgw y wyygyyw y wgwywg", 586},
		{"drvaee t feeatrr o wtbxvt/ggywgw y wywggyy y wgwwwg", 585},
		{"wxtaea i ecigamc a hnniol/gwywgy g yyygyyw w wgwwwg", 584},
		{"lrheel r siaagts h stiaiy/gwywgw y gywgyww w ygwgwg", 583},
		{"qcttee u eiehrue u atsigt/gwywgy w ywygyww w wgwywg", 582},
		{"chiota r reeomsz j nsrhhe/ggywgw w yywgwww g wgyywg", 581},
		{"tlepoi i stagamo r erihec/gwywgw w wywgwyw y wgywyg", 580},
		{"hoivrn t osesori c etecoh/ggyygw w wyygwwy w ygwyyg", 579},
		{"tnoahe g eioioet u hrcnvl/gwywgy w yywgwyw y wgwgwg", 578},
		{"sasgka u hrtaeae y cwardk/gwywgy y wgwgyyw w wgyywg", 577},
		{"daobrm o uuonimg r dteiey/gwywgw w wyygyyw y wgwywg", 576},
		{"dorayi a liylvia e erarnn/gwyygg y wywgyww w yggwwg", 575},
		{"tperde c itlxiio i ecmiia/gwywgw w wwygywy y ygwywg", 574},
		{"sheryp i aoccull u atidyl/ggwwgg w wwwgyyy y wgywwg", 573},
		{"sevepw e grdieio g nrtnmy/gwywgy y yywgwyw w wgwywg", 572},
		{"soofpf r aieftlc i ifsret/gwwwgy y wwwgwgy w ygygwg", 571},
		{"hvscna o ieugatu m rhulue/gwwwgw g wywgwyy y ygwgwg", 570},
		{"vangtd l iygdimi u elohle/ggywgw w wyygwyg y wgwwwg", 569},
		{"uimnlf a ehauten e gdlbnr/gyyygy w ywwgwwy w ygwgwg", 568},
		{"sneekc u tatucdr t pegliy/ggywgw w ywygwww g wgyywg", 567},
		{"dvegyo s eutamgr a uatvst/gwywgg y gywgwyw w wgwywg", 566},
		{"baeleg i creuego s secrlt/ggywgy w ywygwww g wgyywg", 565},
		{"dedipb m frmiuuo f utreoy/gwywgy y yywgwyw w wgwwwg", 564},
		{"srcawu e seoiiet w rtansk/gwwwgy y wwwgwgy w ygyywg", 563},
		{"chnehl s vnaivca c ufiafh/gwgwgw w wyygyyy w ygwywg", 562},
		{"slhekg v fplinla a etrent/gwwwgw w wwggwyy y ygwyyg", 561},
		{"unnepw e eesdrru s udsgrs/gwywgy y yywgwyw w wgywyg", 560},
		{"mtesti u ercoead n ksuclr/gwyggw w ywygwyw g ygwwwg", 559},
		{"wzeoyu a daoccnw r enaomy/gywygw w wywgwyw y wgwywg", 558},
		{"druasd l lyatele o otplsy/ggywgw w gyygwyy y wgwwwg", 557},
		{"sewenr u weonnex e pbhear/gwywgy w yywgwyw g wgwywg", 556},
		{"tebtyi t smlasbo m udapiy/gwgwgy y wyygyww w ygwwyg", 555},
		{"sllhtl g earplal u heetue/gyyygw w wwygyww w wgwywg", 554},
		{"ipertn e reoifrk s oruunn/gywwgg w wywgyyw w ygywwg", 553},
		{"aareet d srelabt i lmruih/gwywgw g wyygyyw y wgywyg", 552},
		{"seegni o phuteoo w uednre/gwywgw y wywggyy w ygwwyg", 551},
		{"cneoca l alabemy i oprmlr/gywygy y yyygyyw w wgwwwg", 550},
		{"syikfn e wlvolai f elrryr/gwgygw w wywgwwy w ggwyyg", 549},
		{"bziler r taratsa o alpeir/gywygw y wyygyyw w wgwywg", 548},
		{"bneyha c municre t ettsha/gwywgy y wwggwwy y ygywyg", 547},
		{"rroeti o abinmpr o gtcoae/gwywgy g ywygyww w wgwgwg", 546},
		{"daeinr t dcnepme c ihigee/gywggw w wywgywy w ygwyyg", 545},
		{"zsyeyr o kesatip e nalbbs/gyyygy g yywgwyw w wgwywg", 544},
		{"paueoi v gwnolhn l aeknnt/gywwgw w ywygyyg w wgwwgg", 543},
		{"rdnnne e neianii s angety/gwywgy w ywygywy w ygwgwg", 542},
		{"dratmu i drtiitt e roeepa/gwyygw w yyygwwg w wgwgyg", 541},
		{"mnlodl s erainhu g orbwuy/gywygw g wywgwyw y wgywyg", 540},
		{"agrvee l krfovfl p oteaay/ggwwgy g wywgywy w wgwywg", 539},
		{"crdegd t lieirir e irnoly/gwywgy y yyygyyw w wgwywg", 538},
		{"nouddy c ioastla m oriral/ggywgw w wywgwyy y ygwwgg", 537},
		{"dttini a eeotmhc r ehdeoe/gwwwgw w wywgwyw y wgyyyg", 536},
		{"wihnfh s rzetino r rtfere/gyywgw w gwwgyyw y wgwyyg", 535},
		{"aselto e cmradrl g awnvlt/gwgwgy y yywgwyy w ygwywg", 534},
		{"asalwp e wropjea c helagt/gwyygw y wywgwgy w ygwwwg", 533},
		{"jreeto e sdwieed n eltruy/gwywgw w wyygyyw y wgwywg", 532},
		{"caceki e lltsaoe i nmhlnl/gwywgy y yywgyww w ygwwwg", 531},
		{"belbtr u aatmorn e utewrl/gwywgy y yywgwyw g wgwwwg", 530},
		{"cecuke r oocdorn t aaamha/gwyygw y wyygwgw w ygwwwg", 529},
		{"wikwnt n nnoonhr j ehceaa/gwgwgy g yywgwyw w wgwywg", 528},
		{"sctrpm e tatobio u sftauy/ggywgw w ywygwww g wgyywg", 527},
		{"adluyk i iclnbio a eelery/gwgwgw g wywgwyw w wgyyyg", 526},
		{"frbnhl o ooemeat o dmiiuy/gwywgw y gywggyw w wgwywg", 525},
		{"ctcrms n drnoaal h rmaihy/gwwwgw y wyygyyw w wgwywg", 524},
		{"snilna r eueiblc a lmwigh/gwyygy w gwwggyw y wgwwwg", 523},
		{"tgheea i osreemt a htigrn/gwywgw w wwgggww y wgyyyg", 522},
		{"damnyg g ererame n ikuled/gwgwgw y yyygyww w ygwwyg", 521},
		{"airdne v irtneeo m icvnae/gyyygw w wyygyyw y wgywyg", 520},
		{"puiweu o toeieeq t hrsaor/gyywgw w yywgwyw y wgwwgg", 519},
		{"mulnsa i ilrboue o tfuily/gyyygw w wywgwyw y wgwywg", 518},
		{"feeonn w rewdinl g edolly/gwyygw w wgygwyw w ygwywg", 517},
		{"cetrlu i haalcrt n epncih/gyyygw y wwwgwww y wgwywg", 516},
		{"smkupm w nknbeui e rgaiey/gyywgw w ywygwyw y wgwyyg", 515},
		{"bexkrd c aemarih k geasat/gywygy w ywygyww g wgwywg", 514},
		{"tuaehl r emrdcnu i heoeby/gwgygw w wyygwww g wgywyg", 513},
		{"fiaclt u eatolhu t ltarae/gwywgw y wyygyyw y wgwywg", 512},
		{"weoakm e hocberm i nprerl/gwwygw y wgwgyyw w ygyywg", 511},
		{"bnueet p moeioaz o sluwer/gwywgw g wywgwyw y wgywyg", 510},
		{"eqebla m eupirel n mdlwal/ggywgw w ywygwww g wgyywg", 509},
		{"sokrrn e nnaigpl u aehgee/gwywgw y wyygyyw w wgwgwg", 508},
		{"reuori e lodewcd e areiro/ggywgw w wyygyww g ygywwg", 507},
		{"cmhett e aagaalp r rtaret/gwywgw y wywgwyw w wgyyyg", 506},
		{"paldes g eenugtu t noroer/gwwwgy w yyygyyw w wgwygg", 505},
		{"baarkk t lcaerxn p redola/gwgwgy y ywygyww g wgwwwg", 504},
		{"wleerr o sapogts e arapry/gwwggw y yywgyww w ygwgwg", 503},
		{"cmnsar i haochwi y etthot/gwywgw y wygggyw y wgwywg", 502},
		{"seostl l seohatn e upeecr/gyywgy w wywgyww y ygywwg", 501},
		{"daieoe e couvowr g glnene/gwywgy g yywgwyw w wgwywg", 500},
		{"gsnutp i uylcria t lhhohe/gwyygy y wgwgwyw w wgwywg", 499},
		{"srucno r eamffly o ehwosn/gywygw y wgwgwgw y wgwywg", 498},
		{"azlade e lorarem a rtsawd/gwwygw y wywgwgw y ygwywg", 497},
		{"raseec l trauenu r arosgy/gwywgy y yywgwyw w wgwwwg", 496},
		{"atiure i ddbuiod e itrour/gwywgw w ygwggww w ygwyyg", 495},
		{"ttnohe c tostadi o uedare/gywygw w wwygyww y wgywyg", 494},
		{"tettpi h motfenr r twiuiy/gwywgw w wwygywy w gggywg", 493},
		{"bisusa t pvhsieu l nsesie/gwywgg w gwygyww w wgywyg", 492},
		{"talbwi l eoebhyr a rtlrey/gwywgy w wwygwgy w ygyywg", 491},
		{"aiemda s alunume a hsnnly/gwgwgy w yywggww w wgwyyg", 490},
		{"sndrdc e mhuamap r regaly/gwyggg y ywwgyyw w wgwywg", 489},
		{"keluei a guoyald d lbfnbe/gwywgw w wyygyyw y wgwwwg", 488},
		{"tnroes o olrtaep r ioszee/gwgwgy y ywygyww g wgwywg", 487},
		{"nllrhm o torduap a ehriyy/gwywgw g wyygyyw g wgwywg", 486},
		{"aoatdl p ttetocr e itutdy/gywwgw w yyygyww g ygwgwg", 485},
		{"mweenc e eiinnyc l roiior/gwywgy w yywgwyw y wgwywg", 484},
		{"loyilm a soedhve e lrbiee/gwyygw g yyygwyg w wgwwwg", 483},
		{"lreays g lzoateu s rspuun/gwywgw y wywgwyg y ggwywg", 482},
		{"cgbmli e uienrea m icggae/gwwygy y wywgwgw y ygwywg", 481},
		{"vouesi r irrdaoa e ialpdn/gwywgg y gywgwyw w wgwywg", 480},
		{"peciki e hirtlue o ntletd/gwywgg y wywgyww w ygwywg", 479},
		{"sdttde l prtboow o lhioey/gwwwgw g wyygyyw g wgwywg", 478},
		{"gaaasa n lrsgrae l ftnled/gwgwgy w yywgwyw y wgywyg", 477},
		{"bgeddt a alvaiul v reolly/gwywgw w wygggyw y wgwywg", 476},
		{"lyldha i aurrcoi l ecdsay/gwwwgw y wyygwyg w wgywyg", 475},
		{"cgnrtu u heeddrg i seoeft/gwywgg y gywgwyw w wgwywg", 474},
		{"beadhe s tcluaxt l uhccrh/ggwwgw w ywygyww g ygywwg", 473},
		{"pumlbe a mlfiyih x atnnle/gyyygw w wywgwyw w wgwywg", 472},
		{"kptaku n nsniita a itgooy/gwwwgy g wwygwgy w ygyywg", 471},
		{"srlirc i hucinvg o cecpet/gwywgy w ywgggww y wgywyg", 470},
		{"aeoaei x elctfpr n dtofol/gwgwgw w yyygwyw y wggywg", 469},
		{"mdcueg y esciail i ncport/gwywgy y ywwgwww w wgyyyg", 468},
		{"bsahzo t etnelni a onaipl/gwwwgy y wwwgwgy w yggywg", 467},
		{"geivle r seastao e idatux/gyyygw w wyygyyw w wgwgwg", 466},
		{"cporke a lnniasl e lgadnt/gwgwgw w wywgyyy y ggywwg", 465},
		{"deiull o aexsvty t relonl/gwgwgy w yywgwyw y wgwywg", 464},
		{"taolye v larrssu w xeaent/ggywgw w wywgwyy y wgwgwg", 463},
		{"fcakha i curunuf h rsinty/gwywgw w wyygyyw w wgwywg", 462},
		{"rgeeni i eidpvvr a ulisae/gwwggg y wywgyww y ygwwwg", 461},
		{"ggrupp a trshdau e rprioy/gwywgw y wywgwyg w ggwywg", 460},
		{"tutuhu l htucole n lbrmry/gyywgy g wyygwww w ggywwg", 459},
		{"beoaho t tinecat c inotwh/gwgwgy w ywwgwwy y ygwywg", 458},
		{"seahtn l aksacie e ptbrhr/gywwgw w gywggww y wgwyyg", 457},
		{"vgtenr e geeuoed o errday/gywygw y wywgwyw y wgwywg", 456},
		{"scepfw a nrgiuor l rtkhue/ggywgw y wwygwyg y wgwywg", 455},
		{"pcrset e rahtero u oeerbr/gwywgw y wyygyyw y wgwgwg", 454},
		{"ccaone e uarbdet e otlcmh/gwywgy y wywgyyw g ygwywg", 453},
		{"mtcolr e eafardg t istuue/gywygw y wwygyww y wgwwwg", 452},
		{"gatnen t evuglrr u adcohh/gwywgy w wwwgwgy y ygyywg", 451},
		{"boicna e leuedna c rhpcay/gywygw w wywgwyw y wgywyg", 450},
		{"rtioer e aeestlu i ucniee/gywygw y wywgwyw w wgwywg", 449},
		{"tdreen g rawlkgi i odvioe/gwywgw w wywgwyy y ygwywg", 448},
		{"gurdtu i oedtleo d iytrol/gyywgw w ywygwww y wgwwyg", 447},
		{"sieleu r ctoictv e vneody/gywygw w wwgggwy w ygwywg", 446},
		{"sllrpe s aedittt e ewaiey/ggywgw w wywgwyy y ygwwyg", 445},
		{"symaro o wpooaea l orxebn/gwywgw y wywgwyg y ggwwwg", 444},
		{"aeamtr s imdioao e bsdxpr/gwwwgw w wygggyw y wgwyyg", 443},
		{"veyrdl i ehgglla t laieir/gwwwgy g ywygyww y wgwywg", 442},
		{"meovei o eiencov m erujet/gwyygw w ywggwwy y wgwwyg", 441},
		{"duirng u dogfged n ehnoee/gwgwgy w yywgwyw y wgwywg", 440},
		{"boocdr i ydrasvd l acolay/gygwgw w wywgyww w yggywg", 439},
		{"rniwig g trranae r nlabbo/gwwwgy w ywgggwy y ygwywg", 438},
		{"baoote s lsaraua t essvre/gywwgw w wyygywy w ygwywg", 437},
		{"pechhr c uacgiot n rfnioh/gwywgg w gywgwyw y wgwywg", 436},
		{"reoots v eeiraue c epctvh/gyywgw y gywgwyw w ygywwg", 435},
		{"mensee r rtwagii d etonvt/gwwwgw g wywgwyy y ygwgwg", 434},
		{"gptayr a orprasw s asunty/gwywgg y wywgyww y ygwwwg", 433},
		{"cyicrh e onlogin n mkraal/gwywgg y gywgwyw y wgwwwg", 432},
		{"coeeod l rneiaax v ltthpa/ggywgw w ywygwww g wgyywg", 431},
		{"maoryc d colmdun k aooiey/gwywgy y yywgwyw w wgwwwg", 430},
		{"fdhotn a cretego e rlapoe/gwwygw w wywggwy g ygwyyg", 429},
		{"stfoti f eqhutie p slgriy/gwywgw y wywgwyg w ggwywg", 428},
		{"artode i snmomtg d iefejy/gwwwgy y wwwgwgy w ygyywg", 427},
		{"nmspys h maaaesl u tlraey/gwgwgy g yywgwyw w wgywyg", 426},
		{"oeeure u inrgsid i atatrn/gywwgy w wyygyww g wgygwg", 425},
		{"seuyka r eznuprn s thcasd/gwgwgy y yywgwyw y wgwwwg", 424},
		{"reodri g aveviro p tdioiy/gyywgy w wwwgyyw w ygwywg", 423},
		{"etemyo g weirele g uthpid/gyyygw w wywgwyw w wgwywg", 422},
		//{"sooeci m emlipsn e ltdrhe/ggywgw w yyggwww y wgwwyg", 421},
		{"sielkr t uuadoin n epcwml/gwywgw w wyygyyw y wgwwwg", 420},
		{"hamele e uoamivt o olyetr/gwwggy w wywgwwy y wgwyyg", 419},
		{"crnsgi e emsarui s nplgns/gwywgy y yywgwyw w wgwwwg", 418},
		{"gosadr a tenisra v gelnue/ggywgg w wwygwwy w wgyywg", 417},
		{"bbrtma o froimuw s pmoeoo/gwwwgw w wyygyyw y wgwywg", 416},
		{"vahmro c isiapan l arlery/gyywgy y wgwgwyw w wgwywg", 415},
		{"snaeem r etletio v henrvr/gwwwgy y yywgwyw y wgwwwg", 414},
		{"peroeo o akndnnl o baenry/gwyygw y wywgwyw w ygwgwg", 413},
		{"pemtob n acvorgn e vhiyaa/gwwwgw w wyygyyw y wgwywg", 412},
		{"woeadt l reabulh r efmwll/ggywgw w wyygwyy y ygwwwg", 411},
		{"hplntt i ganisea r geeear/gwwwgy w yyygyyw w wgywyg", 410},
		{"ssnotl r acataer n atcoxt/gwywgw y gyyggww w wgwywg", 409},
		{"idrare d gkliaot u elnnee/gwywgy y yywgwyw w wgwwwg", 408},
		{"pealnr n ltosaro l aeonyy/gwwygw w wyygyyw y ygwwwg", 407},
		{"ttolbo i uiraego n spharo/gwywgw w wyygyyw w wgwywg", 406},
		{"txrite i iiramct a realpl/gwyggw w yyygwwy w ygwwyg", 405},
		{"thfrmr u ulcocat o etnteh/gwwwgg w gywgwyw w wgyyyg", 404},
		{"tpalti g msourea i rriynd/gwwwgy y wwwgwgy w yggywg", 403},
		{"mmubyc t eecnoui i dreuda/gwywgw w wyygyyw g wgwywg", 402},
		{"miidcr g aognone m alirie/ggywgw w wyygwyy y wgwgwg", 401},
		{"bsmcye s eaiarsl l adeeks/gwywgy y yywgwyw y wgwgwg", 400},
		{"geitte e eunsiun r ahpatr/gwwwgw y ywygyyw w wgwyyg", 399},
		{"bracto i eatmdie u fhdiay/gwwwgw w wyygyyw g wgywyg", 398},
		{"cnuapm a bfeieka f llrlay/gwwygw y wywggwg w wgwyyg", 397},
		{"fmmten e uludnnr a uelriy/gwwwgw w wyygyyw y wgwywg", 396},
		{"crhrhi o oontaca u dsceey/gwwwgw w wywgyyy y wgwgyg", 395},
		{"srlmtr e erhdhei o atehew/gwywgy y yywgwyw w wgwywg", 394},
		{"kcboko y eacnreu a abeank/gywygw w wywgwyw w ggyywg", 393},
		{"cshtfm h dtiaspa p arfaay/gwywgw w wywgwyy w ygwywg", 392},
		{"sdroea o tuktrou p ltipme/gwwygw y wwwgygg w ygwywg", 391},
		{"rdeiri e eeaildr e dorarr/gyyygy w yywgwyw g wgwwwg", 390},
		{"rerior o capoctk e areern/ggywgw y wywggww w ygywwg", 389},
		{"madrlm t oecaelo p aracoh/gwgwgw w wywgwyy w ygyyyg", 388},
		{"sooldm s hliblge e dfiaee/ggwygw w wywgwyy g ygwywg", 387},
		{"crlska a eprpona a hhllnd/gwywgy y yywgwyw y wgwwwg", 386},
		{"batdde e uolwnie r ordnuy/gwwwgw y wyygwyg w wgyyyg", 385},
		{"caehmr n agagrlu l aerury/gyyygg w gwygyww y wgwwwg", 384},
		{"masdro e gyduoir r ictaie/ggywgw w ywygwyw g wgyywg", 383},
		{"roeurr t boaedup o stewir/gwywgw y wyygyyw w wgwywg", 382},
		{"mcahoa i pemisrd e dcheur/gyyggw w wywgyww w ygwywg", 381},
		{"tuerkt o trettri o chtucy/gyyygy w ywygyww w wgwywg", 380},
		{"daspsa w rleievn l etvaok/gwywgy w wyygwyw w ygwywg", 379},
		{"lieocl l fgaashe e vcldit/gyyygy g ywwgwww w wgwywg", 378},
		{"gegrev c zuapmer r aepelt/gwwwgy w wwygygy y wgwywg", 377},
		{"cleitc e ttoglii i aavrhy/gwywgy w yywgwyy g ygwwwg", 376},
		{"seeamu w rlsbrer l mheeoy/ggywgw w ywwgyyw y wgwyyg", 375},
		{"ednref o neiiail k elosfn/gyyygw y wywgwyw w wgwwwg", 374},
		{"gefayr i mrdoaoa i elorvn/gwywgg w wywgywy g ygwwwg", 373},
		{"tuyrgl u nnbnupe a ilycnh/gwywgw w wyygyyw w wgwywg", 372},
		{"vefaoa e lofindc i olfagl/gywwgy w wyygwwy w wgwyyg", 371},
		{"mraowo t tacouoi r anhsch/gwywgy w yygggyw y wgwwwg", 370},
		{"svmter h titerdn a atnipe/gwyggy w wwwgyyw w ygwywg", 369},
		{"dmchye i uamnase a iygtot/gwywgw y wyygyyw w wgwwwg", 368},
		{"fdolea e taeussl a ttluan/gwwygw w ygwgwww g wgyyyg", 367},
		{"namaha y azipgee a lltool/gwywgg y gywgwyw w wgwywg", 366},
		{"vrznat o isioegp e lanvkt/gwywgy y wgwgyyw y wgwywg", 365},
		{"fxrwla o lgaiyir w onnoin/gwywgw w wywgwyy w ygwywg", 364},
		{"rhymtc b uiaopoe t icleue/gwwwgw g wywggyy y wgwwyg", 363},
		{"cnelgg u arnoden l asrsme/gywygw w wyygyyw w wgwwwg", 362},
		{"giealn t lvgptir a elaude/gywwgw y wgwgwyw w yggywg", 361},
		{"fiiuhc l livvaer l asoito/gwywgy y yywgwyw w wgwwwg", 360},
		{"smneka e kuibrlm a npeukl/gwywgw w wyygwwg g ygyywg", 359},
		{"cicame b iiyobat l rnsaoe/gywygw w wyygyyw w wgwywg", 358},
		{"ceroec t eahtuak r hechor/gwyygy w yyygwww w ygwwgg", 357},
		{"gtoage t nnlseio l idekny/gwywgw y wyygyyw w wgwwwg", 356},
		{"snroff h eircnac u uleuad/ggywgw w ywygwyw g wgyywg", 355},
		{"soeted t oortrta u iwkceh/gyyygw w wyygyyw y wgwwwg", 354},
		{"alvgde n etcatcn o eliiuh/ggywgy w wywgwyy y wgwwwg", 353},
		{"sghsla l eclyuid l tpmire/gwwwgy y yywgwyw g wgwywg", 352},
		{"grnohp h sarhsut e elguoe/ggywgw w ywygwww g wgyywg", 351},
		{"sewmne e rrvbrmo e htrwee/gwywgy y yywgwyw w wgywyg", 350},
		{"dorrlr o eeviplk c itlned/gyywgw y yywgyww w ygwyyg", 349},
		{"sreamr a irrotcn g ffadwy/gyyygw y wywgwyw w wgwywg", 348},
		{"aonimw e relfrwi a ueexee/gyyygg y wwygwyw w wggwwg", 347},
		{"sutpts o eslicad x meravy/gywygw y wywgwyw y wgywyg", 346},
		{"grcief l nboipar v rtaevt/ggwwgy w wywgwyy w wgygwg", 345},
		{"pdeare d oweagpr e enwevy/gwywgw w wyygyyy w ygwgwg", 344},
		{"aoudts h egmipse f utdpnt/gyyygy w ygwgwyw w wgwywg", 343},
		{"bgoidn s eassoro a xeltll/gwwwgw g wyygyyw y wgwgwg", 342},
		{"grsenn e suetfaa l nhcroe/ggwwgg y ywygwyy w wgywwg", 341},
		{"betdkl h itraane s cenrvt/gwywgw w wywgwyw w wgyyyg", 340},
		{"paeure l ogyirmn m fperan/ggywgw w ywygwww g wgyywg", 339},
		{"ppsees a axsucec r batdut/gwywgy w ywygyww y wgwywg", 338},
		{"baevys t idloede o otaafl/gyywgy y wwwgwgy w ygyywg", 337},
		{"stniec t pexieel r tlhigt/gyyygw w wgwgwgw w wgyyyg", 336},
		{"dbjurm g merneaf i ogouey/gwwwgw y yywgwyw y ygwywg", 335},
		//{"mlaran i aelvnav a ucieey/gwywgy w yyygyyw w wgwywg", 334},
		{"blssdy h iilsasa e ocuaey/ggywgw w yywgwyy y wgwywg", 333},
		{"tkluec l hesoojv e seclet/gwwwgw w wyygyyw y wgyyyg", 332},
		{"oaeerr l frlidft e arftry/gwwggg y wywgyyw w ygwwwg", 331},
		{"wteitd p tehuaco r cneeeh/gwgwgy y yywgwyw y wgwwwg", 330},
		{"tdrpll o mfiipoi m rcsuoy/gwywgw y ywwgywg y wgwwyg", 329},
		{"qacuht d idsmnic a uliuah/gywygw g wywgwyw y wgwywg", 328},
		{"deepyi a gitesce c ioilld/gywwgg y wywgyww y ygwywg", 327},
		{"snloll o pgwlaao l oywtay/gwywgw y wwygywy w ygywyg", 326},
		{"cdelnr e uridegu d hddnoy/gwwwgw w wywggwy y wgyyyg", 325},
		{"vytyla s ioeiena a olsewr/gwywgw y wywgwyw y wgwywg", 324},
		{"tbpihl n dtwliee i oagohy/gwwygw g ywygwyw y ygwwwg", 323},
		{"sptkhw c rnstuap i lyeooy/gwwwgy y yywgwyw g wgwywg", 322},
		{"stnlpi p nrnmoau a etseee/ggywgw w ywygwww g ygyywg", 321},
		{"siuemr i raiboah b otchtf/gwwwgw y wwygywy g ygwywg", 320},
		{"slloka p scsuheo e nreurl/gwwwgy y wwygwgy w yggywg", 319},
		{"mnwnrk s laioekf s iaoany/gwywgw w wywgwyy w ygywyg", 318},
		{"mnlisc c juonuai x heecil/gwwwgy y wwwgwgy w ygygwg", 317},
		{"lllrna e boeieon f ilmkcy/gwwwgy y yywgwyw g wgwywg", 316},
		{"fitehr p aasuipq i olmeld/gwwygw y wywgwgw g ygwywg", 315},
		{"ptrroa i eidepae d lrlnly/gwywgw w wyygyyg w ggwwwg", 314},
		{"coniew e rmunruh o ethese/gywwgw y wgygwyw y wggywg", 313},
		{"hraena y eaacopn e erpney/gyyygw w wywgwyw y wgywyg", 312},
		{"paalel n xrodceu u pediry/gwwwgg g ywygwww y ygwwyg", 311},
		{"csroeu z votoaen f aeertr/gwgwgw w wyygyyw w wgywyg", 310},
		{"raumre u labglel r oauary/gwywgw w ywwgyww y wgwyyg", 309},
		{"bleglc n riabaao e ypciee/gwywgy y yywgwyw w wgyyyg", 308},
		{"beohls e llallva e ittsae/ggwwgy w wyygwwy w wgwyyg", 307},
		{"ucrwgd l eellori e ursenn/gwywgw w wyygyyw g wgwywg", 306},
		{"srgmfk o mtreroo p pdaoae/gwwwgw y yywgwyg y wgywwg", 305},
		{"timied r lsegnnd e atseoy/gwwwgw y wyygyyw w wgwywg", 304},
		{"eelarx l hmgiuun n itoese/gyyygg w wwwgyww w ygwgwg", 303},
		{"chneki t esisenu a eflucd/gwywgy y yyygyyw w wgwywg", 302},
		{"wcxlet a rhhgiet y ihrnea/gwwwgy g yywgyww w wgwyyg", 301},
		{"agdrml r ueianeu l oeibrr/gwywgw y wwygywg w ggwywg", 300},
		{"sitnpp t rovewtn n uerory/gwywgy w wwwgwgy w ygwygg", 299},
		{"crouto u baicuan t tcnagy/gyyygw y wywgwyw y wgwywg", 298},
		{"gacftp o esuthrr p oecodh/gwwwgy y wwwgwgy w ygygwg", 297},
		{"awrraa t sotaisc o trleah/gwgwgy y ywygyww y wgwywg", 296},
		{"nnthys a wauortk s alammy/gwywgy w wywggyw y wggwwg", 295},
		{"uchkre s teinoan n olkiey/gwgwgw w wwygywy g ygywyg", 294},
		{"grttns e ixeiduc t rdteey/ggywgw y wyygwyw w wgywwg", 293},
		{"bmatdm s arpawil l mezley/gwywgw y wywgwyy w ygwwwg", 292},
		{"lecmtr e irotoei a htehpw/ggywgw w wywgwyg y ygwywg", 291},
		{"gnvltw u imyoreo s atsert/gyyygw w wgwgwgw w wgywyg", 290},
		{"bldesy l aeeifar e rdxhsr/ggyygw w ygygwwy y wgwwwg", 289},
		{"uiarem i nxzbeor i npenil/gywygw y wwygyww w wgyyyg", 288},
		{"iaieoe o inlmult g erderr/gwwwgy w wywgwyy w ggwyyg", 287},
		{"gcclla w ctoenro a rmateh/gwywgy w yywgwyw g wgwywg", 286},
		{"ntrnho i rlovelm p uhyiey/gywygw w ywgggwy w ygwywg", 285},
		{"goerrv i solrdaw l islaiy/gwywgw g wywgwyw y wgyyyg", 284},
		{"lcnnhe m ropisha e osaued/gwywgw y yywgwyw y ygwwgg", 283},
		{"vapmrd l neaalue i legley/gwgwgw g wwygyww w wgyyyg", 282},
		{"wnidwe d iaiieeo f rrgcge/gwyygy y gywgyww w wgwwgg", 281},
		{"frinta u lnonnia n lteeet/gwywgw y wywgwyw y wgwywg", 280},
		{"cltohr e ootsaon c ahldny/ggyygw y wywgyww w ygywwg", 279},
		{"yehraa k eweaamc n lnukcd/gwywgy w yyygyyw w wgwgwg", 278},
		{"usnder m uaegecn a geongt/ggywgw w wywgwyy y wgwwyg", 277},
		{"vashme e uonieeg n isroor/gwywgw y wwygyww y wgwywg", 276},
		{"iganrd l trseoau c utusny/gwyygw g ywygwww y ygwwwg", 275},
		{"duernr l eimtaee o tdvvee/gwywgg y gywgwyw w wgywyg", 274},
		{"bknhda i aemrsaw e oseial/gywwgg w wywgyww w ygwyyg", 273},
		{"ondfrd a laoieaf e glgnel/gwgwgw w wywgwyy w ygyyyg", 272},
		{"piltaz i nzonoca a ghvale/ggywgw w ywygwww g wgyyyg", 271},
		{"stnrkc e tpcevib s hepoiy/gwwwgy y yywgwyw g wgwywg", 270},
		{"screfm m jlaoeai e atctrh/ggywgw y wywgyyw w wgywwg", 269},
		{"rbyadi m eaernec l stihue/gyyygw w wwygyww g wgwywg", 268},
		{"delutl u cedobak a areelr/ggywgw y wywgyyw y wgywwg", 267},
		{"togaoc e ehbdiia a ttaeur/gyyygy w ywwgwwy y ygwgwg", 266},
		{"itthem o ueserfa e nrlbor/gwywgw w wyygyyw w wgwygg", 265},
		{"gluepr i itsdhan r usnouy/gwywgg w gywgwyw w wgyyyg", 264},
		{"deabnu c wonisti r dtrhee/gwgwgy w wyggwyw w wgyyyg", 263},
		{"veptte o irsulei i arffsr/gwwwgw w wyygyyy w ygwgwg", 262},
		{"moeglo m hatmpti t otaoeh/ggywgw w wywgwyy y ygwgwg", 261},
		{"cuenmh r rdcocrr t ntaafh/gwwwgw y wywgwyy w ygwywg", 260},
		{"haloye a evolyoa d vreoil/gyywgy y ygwgwyw w wgwywg", 259},
		{"mnoirt i deaeold w oreroo/gwywgy g ywwgwww y wgywyg", 258},
		{"salvec o engaode t vplact/gyywgg w ywwgyww w yggywg", 257},
		{"vresde d adauaop a indgey/gwywgg w gywgwyw y wgywyg", 256},
		{"cilueo p eyaarti a tnhdwn/gyyygw w ywygwgg w wgwwwg", 255},
		{"sennkn x croozla n retewt/gwywgw w wyygyyw g wgwgwg", 254},
		{"trraed r gfiihsa e ptniht/ggwygw g ywwgwwy y wgwwyg", 253},
		{"leerch e eiinage r itliid/gwywgy w yywgwyw y wgwywg", 252},
		{"spmino h hogidfc u ntpeit/ggywgw w ywygwww g wgyywg", 251},
		{"apseeu o sidpupr m hnsere/gwywgw w wywgwyw w wgyyyg", 250},
		{"cahykp n orloaga e asetek/gwwwgw w wwwgyyy y ggyywg", 249},
		{"balseg b oevmiui o olgkbe/gwgwgy y yywgwyw y wgwwwg", 248},
		{"mrirha e nigvagi e reesee/gyywgw w ywwgyyw g wggwwg", 247},
		{"gavpoe h uttaniw e rteswd/gwywgw g wywgwyw y wgyyyg", 246},
		{"soeten l reehets o afrahl/gyywgw w wgwgwyw y ygyywg", 245},
		{"wlcaea b eecoeld v jehndt/gywygy g yywgwyw w wgwwwg", 244},
		{"ccanfe o elnlaat i trfaty/gwwwgy w wwygyyy y wgwygg", 243},
		{"shunpu c aibbamr m rdlree/gwgwgw w wyygyyy w ygwywg", 242},
		{"ashhal n sneogps s itllre/gwwggw y yywgywg w ygwwwg", 241},
		{"sinegn d ragdeou g iwline/gwywgy y yywgwyw w wgwywg", 240},
		{"snroea a eoprrnt c alruth/ggywgy y wywgywy w ygwywg", 239},
		{"omdute h btourbn b drtuiy/gwywgy w ygwgwgw y wgwywg", 238},
		{"bnoays r auseses r rsnett/gwywgw y ywwgwyg w wgwyyg", 237},
		{"sounry a ecnpilm i ktaatn/gwywgw w wywgwyw y wgywyg", 236},
		{"ecedle c vxxoalc e ttreeh/gyywgw y wywgywg w wgwgyg", 235},
		{"trenha d rgediud r inoeay/gwywgy w ywygyww y wgwywg", 234},
		{"prshnc n nililoe e ohcage/gwwwgy y wwwgwgy w ygyywg", 233},
		{"suknef t obeomat a tehear/gwwwgw y wywgwyy y ygwywg", 232},
		{"mtottp l aloolss i dhrroy/gwwwgy y gwggwyw w wgwyyg", 231},
		{"bekeeu r rfldler r rfoady/gwywgy g yywgwyw y wgwwwg", 230},
		{"bscrhi j eeanfnr i atusih/gwywgy y wywgyww y ygwywg", 229},
		{"lrauhu o eobcece r idudcy/gywygg w gywgwyw y wgwwwg", 228},
		{"fnltel t raruemd e eddoly/gwywgw y wwwgyyw w ygwywg", 227},
		{"caaotn o sswirlo u itlnbl/gwwwgw y wywgwyy y ygwgwg", 226},
		{"teaodt o lneinor p alnoir/ggywgw w wywgyyy y wgwwwg", 225},
		{"eeqxps n attlrao o leiuil/gwywgy g yywgwyw w wgwywg", 224},
		{"swrapo o nninfit e lfoust/gwywgw y wywgwyy g ygwwgg", 223},
		{"singtr a eeotolm f rlplso/gwywgw w wywgwyy y ygwwwg", 222},
		{"apemth s peoknra l etnade/ggywgw w wyygyww g ygwywg", 221},
		{"tahlet e eeeftud e ihnrrr/gwywgy g yywgwyw w wgwywg", 220},
		{"gsnpyu v tmniotm u uetrry/gyywgw w wywgyww w ygywgg", 219},
		{"mleire a aenaeem r ktkcon/gwywgg w gywgwyw w wgyyyg", 218},
		{"tcsuer d pcotoal r etaouh/gwywgg w gwygyww y wgwywg", 217},
		{"seseeu m rgeiinw e arasvr/gwywgw g wywgwyy w ygwgwg", 216},
		{"fenedl e tltsiur a elipox/gwwwgy y ywygywy w ygwywg", 215},
		{"denott u runeaeg r ptoefr/ggyggw w wwygyww y wgwywg", 214},
		{"crlens e eatalmf i ofhsay/gwyygw y ygwgwyg w ygwwwg", 213},
		{"budkyk u octpoii g edilay/ggyggw w wyygyyw w wgwywg", 212},
		{"tteidl n rreaaim m uprpny/gwyygw g wywgywg w ygwwwg", 211},
		{"vepdos v rreilie v daitmt/gywygy w ywygyww g wgwwwg", 210},
		{"baelnt r encacta r ereioh/ggywgw y wywgwyy w wggwwg", 209},
		{"kooaoo a uewbezr t larbad/gywygg y gwwgwww w wgywyg", 208},
		{"dbluyi e gladoee r italld/gwgwgy y wwwgwgy w ygyywg", 207},
		{"acalei e epdswrs u bdtiht/gwwwgy y yywgwyw g wgwywg", 206},
		{"pwaeyk e treruac s narasy/gwwygw y wwygwyw y gggywg", 205},
		{"camrmq e neauloo l atlday/gywygw y wywgwyy y ygywyg", 204},
		{"pelree g agndisu g eleray/gwwygy w wyygwww g yggywg", 203},
		{"nlacev d rideobl e ariany/gwywgw g wyygyyw w wgwywg", 202},
		{"snevrl e hleiegy g eltdey/gwyygy w wyygyww y ygwwyg", 201},
		{"lieirs w riipese n rcouye/gwywgw y wygggyw w wgwywg", 200},
		{"cleetu r lotilsd v csncie/ggywgw w ywygwww g wgyywg", 199},
		{"gcieoe n uffcvso c aetakt/gyyygw w wgwgwgw y wgwywg", 198},
		{"grernr o rltdavd i oheiae/ggywgy y ywwggyw w wgwwwg", 197},
		{"bcuths w taieccl t mloaeh/gywygy g yywgwyw y wgwywg", 196},
		{"slmhlt u usaofov d epilge/gywygg y wwwgwyw w ygwgwg", 195},
		{"msioeg e ecughor t eoertt/gywygw w wwwgwwg y ggywyg", 194},
		{"lroaeg e aapocnd e rtmnrt/gwywgw y ygwgwyw w wgwyyg", 193},
		{"furrhe n kioffei l lditty/gwywgy w yywgwyw w wggwgg", 192},
		{"urtigh a teneetn r rrtvsy/gwyygw w wywgwyw g ygywwg", 191},
		{"peiori t tcaoese h coiswn/gywygw w wywgwyy y ygwywg", 190},
		{"benodc i ocktirl a umpery/ggywgw y wywggyy y wgwwwg", 189},
		{"eehacv a vunltvs i herwey/gwgwgw g wywgwyy w ygywyg", 188},
		{"uetula r niamatn h alegse/gwyygw w wyggwyy w ygwwwg", 187},
		{"ciuito i eenniva m lcierd/gwywgw y wywgwyw w wgyyyg", 186},
		{"ctrsrp g ierosam i atnejy/gwywgy y ygwgwyw w wgwywg", 185},
		{"beakde i ylfiere a htfdnr/gyyygy w yyygyyw w wgwwwg", 184},
		{"aaetrf a gaiigaa g tnnenl/gwyygw g ygwgyyw w wgwwwg", 183},
		{"tecuty u nwacsdi r rlfray/gwywgw g wywgwyy w ygywyg", 182},
		{"canrkp n meaisao a lpderd/gyyygw w wyygyyw w wgwgwg", 181},
		{"sluplo k aereptn i rnptwy/gywygy w ywygyww y wgwgwg", 180},
		{"rbhllu o seiaete r itvpne/gwwwgy y wywgwgw w ygyywg", 179},
		{"blassn a tvyllas r csioie/ggyggw w wywgwyy w ygwwwg", 178},
		{"fuiias l ltlflnl o pharfy/gwwwgy y yywgwyy y ygwwwg", 177},
		{"wwaeya e arttiro r xkanrn/gwywgy w yywgwyw y wgwywg", 176},
		{"srteep g xlaiixn e hrvpat/gwywgg y gywgwyw w wgwywg", 175},
		{"msuhri r ngiacln i aoecie/gywwgg w ywygyww g ygwywg", 174},
		{"slkpte l dniiguh e tllere/gywygw g wywgwyw y wgwgwg", 173},
		{"hmoiee m usrbvnr s otiuat/gwywgw g wywgwyw w wgyyyg", 172},
		{"wdelra u vhilrea v nkseal/gwywgw w wyygyyw g wgwgwg", 171},
		{"aouwrg o asuirug n neloge/gwywgw g wywgwyw g wgywyg", 170},
		{"mdtiha e eeoirsh o nnucge/gwywgg y gywgwyw w wgwywg", 169},
		{"gracef r eefahzl i dtjtmt/gwwwgy g yywgwyw y wgwywg", 168},
		{"reneto m cgcosae r hhysue/ggwggw w wywgwyy y ygwywg", 167},
		{"sudskt e eelonha n aperlt/gwywgy y yywgwyw w wgyyyg", 166},
		{"vnauto a eelsnae t aenaun/gyyygw w wyygyyw y wgwywg", 165},
		{"noaeev o oesrolc p glishe/gwywgy y yyygyyw w wgwywg", 164},
		{"greodi e tgdapru i dnstay/gyyygy w ywgggww w wgwwwg", 163},
		{"forene i lsovail d aeerir/gywygw w wywgwyy w ygwgwg", 162},
		{"fhtrht i pesgllo i ahrooy/gwywgy g ywwgwwy w ygwywg", 161},
		{"rfulyd j rdoodri x oeeepl/gwywgw w wywgwyy w ygywyg", 160},
		{"cvsdea e aelphhm a ftrsle/gwywgy y ywgggww y wgwywg", 159},
		{"dasiea l ieevdii r itenge/gwywgw y wywgwyg w ggwywg", 158},
		{"pkegec n oettiva i ahrsre/gwwwgy y yywgwyw g wgwywg", 157},
		{"seyatt s etetaar a eprwuy/gywwgw w wwygyyy y wgywwg", 156},
		{"geolne e rmablew e enrldy/gyyygy y yywgwyw w wgwywg", 155},
		{"pslaer o oaucluu e kasael/gyyygw w wwygyww g wgwywg", 154},
		{"setrta v hwhaeil i wmiafe/gwwwgy g yywgwyw g wgwywg", 153},
		{"mreaob u scbrnze o gomiae/gywygy g ywwgwww y wgwywg", 152},
		{"cnnlga g iueibcl i prrory/gyyygg y gwwgwww y wgwwwg", 151},
		{"sidrnt t taroaaa n nfcofy/gywwgw y wgygwyw w ggwywg", 150},
		{"gcuedi l lvuitba o radoir/gwywgw w wywgwyy g ygwywg", 149},
		{"felusl a snitrll t ohaocy/gwywgw y wyygyyw w wgwywg", 148},
		{"sehheo o ordtovh o ntpuew/gwywgy y ywygywy w ygwywg", 147},
		{"algirr l nedirdu n uoeedr/gwgwgw w wwygywy g ygywyg", 146},
		{"adshde b glkaiur k omznae/gwywgw w yywgwww g ygywyg", 145},
		{"gdtlde q priueee a ettreh/gwwwgy w yyygyyw w wgywyg", 144},
		{"seaolt g tesinxy s aeeeir/gywwgw w wwygyww g ygyywg", 143},
		{"wmcrna a goimtoc a etoesh/gwwwgw g wyygyyw y wgwywg", 142},
		{"faaelr i ceabtoa s rhieth/gyyygw w wyygyyw w wgwywg", 141},
		{"axpgei h nploicl v alrint/gwgwgy w wwygyyw w ygwywg", 140},
		{"eelrts e xnthert s aesauh/gwywgy y wywggww y wgwywg", 139},
		{"terhhr o rardroc e ewduiy/gwgwgy w ywygyww g wgwywg", 138},
		{"cbfeea t nvaornu h nemrdy/gwwwgy y gwygwyw w wgwywg", 137},
		{"daaerr o edpoami r etubbo/gywygw y wywggww y wgwywg", 136},
		{"gsrlsl n erodgel o eteary/gywygw y wywgwyw y wgwywg", 135},
		{"gnlrte i tureaan t oelpdr/gywwgw w ywygyww y ggwywg", 134},
		{"carogo n diibden r ualncy/gwywgw w yywgyyw w wgwgwg", 133},
		{"stteei o ognliou r xdeopl/gywwgy y ywggyww w ygwgwg", 132},
		{"spudyi u mtoilmu w olpmoy/gwywgy w ywygwgw w wgygwg", 131},
		{"mrteyb d eenoiel d rtnaad/gwyygw w wywgwgw g wgyywg", 130},
		{"clemha v sssiseu r asdkry/gwywgy y yywggww w wgywwg", 129},
		{"leaori y aeeeeak k glatwn/gyywgw w gyggwww y wgwywg", 128},
		{"vueiet e iiimliv a sdeotr/gywwgw w wywgwwy w yggwyg", 127},
		{"mlnedt l rnidueo o ularoy/gwywgy w wwggwwy w ygwgyg", 126},
		{"fwdonl o lottpre a recukh/gyyygg y wwwgwgw w wgyywg", 125},
		{"fsaefp t eltsnof u ntaury/gwwwgw y wwwgyyw y gggwwg", 124},
		{"scalkn e letiafa m nfigel/gygwgw y wywgywy w yggwwg", 123},
		{"mhiele t enmaarc a dharkd/gwwygw w yywgwwg y wgyywg", 122},
		{"peetdr u aattloe p vlaara/gwywgw w wywgyww w wggwyg", 121},
		{"gacuel o rrnlawl o aymmay/gyywgw w yywggww g ygwwyg", 120},
		{"eeatsl r tehuugl o arntay/gwyygw w wywgwyw w wgwgyg", 119},
		{"tcteeb h rcetsot a hoeolr/gwwwgw y wyggwww w ygyywg", 118},
		{"raueta t eltcuil o leuvce/gwyygw y wywgwww w ggwwwg", 117},
		{"trcalt l caoatet c elovrh/ggwwgy w yywgyww w wgwywg", 116},
		{"teerot m echurao r debtvt/gwywgw w ywwgwww y wgwywg", 115},
		{"peuodn g ieltunn g oedory/gwgygw w wywgywg w ygwwwg", 114},
		{"sovonc o crrteie c tmrrue/gywwgg y wgygwww y wgywwg", 113},
		{"liaada e prvnsrk l ehaeue/gyywgy g wwwgwyw y wggwwg", 112},
		{"qtrika t rmpaigu e ilreuy/gwyygy w wwggwwy w ygygwg", 111},
		{"weurla e nglninr e ugohwe/gyywgw y wwwgwwy w wgwwwg", 110},
		{"fkolya n ihsnanc i jtiuot/gywwgw y wwwgwww y wgwwyg", 109},
		{"yeletr s laioknl n usacny/ggwwgw w ywwgyyw y wgwygg", 108},
		{"atitni n dlftine r ogemeh/gwywgw w wyggwgw y wgwywg", 107},
		{"tbeoto l eilbrea a msurnl/gwywgg y wywgyww w wgwwwg", 106},
		{"casetm c slafeih e rtinoe/gwyygy w wwggwyw y ygwgwg", 105},
		{"hpitoa i evenppr o idyced/gyywgw w wwwgyww w ggwyyg", 104},
		{"biiila r veegiey l erleac/gwywgg w wywgwww y wgyywg", 103},
		{"slngnd o uioisqi h abpext/gwwwgw y wwwgywg w wgwgwg", 102},
		{"gbppto d ennisew r asnerd/gwwwgy y yywgwgw w wgygwg", 101},
		{"mmkoye u iaomerr o pahcln/gwywgw y wyggwyw w wgwwwg", 100},
		{"gnagmm o roregne r asatsl/gwywgw y wwwgyyw w ggywwg", 99},
		{"ceyasp e mldphor u rseuap/gwwygw y wwwgwyy w ygywwg", 98},
		{"cteith c tearala g eheehr/gwgwgw w wywgwwy y ygyywg", 97},
		{"stacho t lceftei r rweofh/gywwgw w wyggyww y wgwywg", 96},
		{"uilidg n naeadpa n crpire/gwwggw y ywwgwyw w ggwywg", 95},
		{"begahc r clniykx n oelaee/ggywgw w ywygwww g wgyywg", 94},
		//{"grulsa s mlpblai l mtenet/gwwygw w wywgwwy g wgywwg", 93},
		{"plsxal n tndisza g eergat/ggywgg w wywgwwy w wgywwg", 92},
		{"pmcaen u ulrcuit c xkrrna/gwywgw y wywggww w ygwgwg", 91},
		{"seroee v vecimct g leljut/ggywgw w wywgwyy y wggwwg", 90},
		{"besoli e enikoar e adwror/gwwygw w ywwgwyg g wgwwwg", 89},
		{"lplrhi a ecuameh f cdtufy/gwywgy y ggwgwww w wgwywg", 88},
		{"cnnsec v gneaple r akinht/gwwggy w wyygwww w wgwywg", 87},
		{"haondw r rseoeoe a tevkpy/gywwgw w wgwgwyw y wggywg", 86},
		//{"quaatd e usroedl g hhbrue/gggwgw w wywgyyw w ygwwwg", 85},
		{"clubsa n souirer p tagenr/ggwwgw y wywgygg y ygywwg", 84},
		{"roaala a oeltbvn u itiein/gwyggw w wywgyww w ygwwwg", 83},
		{"bcstda a ieuotln e dnrloy/gwywgg y gwygyyw y wgwwwg", 82},
		{"sclitr t meeadia a rnpdre/gwyygw y wywgywg w ygwwwg", 81},
		{"cawaya e euntbed i ocheal/gwywgw y yywgyyw w ygwygg", 80},
		{"ppmiel s nrmegle u isasel/gwwwgw w wyygwwy w ggwwyg", 79},
		{"ovrcen c eicnnuo e irauxl/ggywgw w yyygwww g wgyywg", 78},
		{"trauya i nkismec i udddiy/gyywgw w wwygyww g ygywwg", 77},
		{"wrdhhi e eolpmts u yrmrae/ggwwgg w wwwgwwy w wgywwg", 76},
		{"costml i mluaiaa l whssty/gwwwgg y wwwgwyy w wgwwyg", 75},
		{"uwwide f eemdlgg n etunet/gwwwgy y yyygwyw w wgwwgg", 74},
		{"greaep u mratosa i rtolee/ggwygw w wywggwy w ygwyyg", 73},
		{"cacipw t lmnsler a iltuee/gwwwgy y wwwgggy w ygyywg", 72},
		{"wtechu i liepmnf i ufhtgh/gwywgw y wgwgwyg w ygwywg", 71},
		{"afoole a salmwrs w ohsrue/gyywgw w ygwywyg w wgygwg", 70},
		{"rnuene e bdrungm g alooue/gwwggg w wywggyw w wgwyyg", 69},
		{"bioooy e oteseer n rdnugr/ggywgw y wywggyy y wgwwwg", 68},
		//{"saoold n poweinc e ufoacr/gwgwgw y wgwgwgw w ygwywg", 67},
		{"ssalal u parusdr i ptmtny/gwywgw y ggwgwyg w wgwwwg", 66},
		{"foeili s eonalab r groscr/ggwwgg w ywwgwwy w wgywwg", 65},
		{"sitatd i genicla i rrheld/gyywgw y wgwgwyg w ygwwwg", 64},
		{"bllvkr a torevps i ntoace/ggwwgw y wgygwyg w ygwwwg", 63},
		{"clrups r naatcml o rpeule/ggywgw w yywgwww g wgyywg", 62},
		{"chpeda l rlaaxta v irlcih/ggwwgw y wywgygg y ygywwg", 61},
		{"tebike e uaclurd e nllehd/gwwygw w wywgwww g ygwywg", 60},
		{"mardhd g indiade t aceacy/ggywgy w wyygwyy y ygwywg", 59},
		{"gleehy e anraocp t anresl/ggwwgw g wywgwyw w wgwwyg", 58},
		{"rssonl e iheinoo b amrrue/gwwwgw w ywwgwyw w wgwywg", 57},
		{"delerr i uyaoneu c alrder/gwwggw y gwwgwyw w wgwwgg", 56},
		{"iaraci h lcmetep e dylsrs/gwwggw w wgygwgw w wgywwg", 55},
		{"aplttd e eeeodds g errsny/gywwgw y gywgwww w wgwwwg", 54},
		{"guahmp l dnrtear e otueam/gwywgw w ywwggyy g wgyywg", 53},
		{"ranrhg r uoobaer e emlamy/gwywgw g wwwgyyw w wgwywg", 52},
		{"miimce l ouegrer o araawy/ggyygy y wwygyww y ygywwg", 51},
		{"ldraly s oaoreat w atsloy/gwwggw y ggygwww w wgywwg", 50},
		{"dsathp i ebiseet n otecuh/gwwggw w wgygwww w wggwwg", 49},
		{"mhsioo i eruusbt t rlacre/gwyygw w ygwgwyw y wgwywg", 48},
		{"mrhyac c gniaiai i tcetfc/gwywgw y wwwgwwg g ygwwwg", 47},
		{"srduni e riocaer e ncivey/gwwwgy w yywgwyw w wgwywg", 46},
		{"fnrhta r rlagoos o urtegy/gwywgw w wyygyww y wgyywg", 45},
		{"sncemn c neligin o uprrae/gwywgw w ywwgwyw w wgwywg", 44},
		{"tsperk f aexohae y itkoan/gwwggw w ggygwww w wgywyg", 43},
		{"klados a tehstcy e aikzol/gwywgw w yywgyyw y ggwywg", 42},
		{"meeleo r aeatech a troenr/ggyygy y wwwgwyw y ygwywg", 41},
		{"satemu r aeagbby c abugre/gyyygy y gwwggyw w wgwyyg", 40},
		{"cmroac s opmiorc o heepdt/gwwggw w ygygyyw w wgywwg", 39},
		{"stcalu w tlldear i aetelh/gwwwgw w yywgwyw w wgyywg", 38},
		{"qtguly u gduioet n eneily/gwwygw w ywwgwyw w wgwywg", 37},
		{"frlels o eidinoi g ltmuar/ggywgy y ywwgyww w wgyywg", 36},
		{"crhamt t bunokll r ietray/gyyygy y wwwgwgw w ygyywg", 35},
		{"fslahm e gllikan l uevgay/gyyygy y wywgwyw g ygwywg", 34},
		{"prhnya e dweanos e kkurhl/gwywgy y yywgwyw w wgwwwg", 33},
		{"datrmu y tsaacro e revovr/gggwgw w wwwgwyy w wgwwwg", 32},
		{"diloyn k tladreu e iynaws/gggwgy w ywwgyyw g wgyywg", 31},
		{"luuhet e apgraut e olsmny/gwyggw w wgygwyw w wgywwg", 30},
		{"aeaayo a lelrvls c rretet/gwywgw g wywgwww w wggwwg", 29},
		{"mldaht o rnotial e utnuty/gwwwgw w yywgwyw w wgwywg", 28},
		{"fainlu e oseorve e esrdty/gyyygy y wwygyyy w ygwywg", 27},
		{"elcutr i ahxourl m atcghe/gwwwgw w ywwgwyw w wgwywg", 26},
		{"setnei o hoetteb r ndrlay/gwwggw w wgygyww y wgywwg", 25},
		{"frjodn r teihhic i udttey/gyyygy y wgygwww w ygyywg", 24},
		{"idsvrc n nlmoria r aegfee/gwwwgw w ywwggyy g wgwywg", 23},
		{"pxamen t urrbrlo w odiabl/gwwwgw w wwwgwww w ggwgwg", 22},
		{"vuemtr r eeetgio e reovrt/gwyygy y wyggwww g ygwwyg", 21},
		{"kaayka s elultat n idctey/ggyygy y wwwgyyw w ygwywg", 20},
		{"eothss y olrluoo x ctgsit/gyyygy y wwwgwgw w ygwywg", 19},
		{"clrial i aurpewe h ayzrcd/gwgygw w ywwgwyw w wgwwwg", 18},
		{"boedts n ahoagya e rwalel/ggywgw w ywwgwwg w wgwwgg", 17},
		{"sdrder i oipdepf l igiray/gwywgy w wywgwww w ygggwg", 16},
		{"yiyltu e vharakl c isocpt/gwwwgw y wwwgwwy y ggwwgg", 15},
		{"siatno y odhdver h etrmoe/gyyygy y wwwgwyw w wgwywg", 14},
		{"dggoam e gioinwn h tllelt/gwgygw w gwwgwww w wgwwwg", 13},
		//{"arcxet b ezmonje n aezodt/gwwwgw w yywggyw g wgwywg", 12},
		{"cldara h dxopeul i vreeey/gwwwgw w ywwgwyw w wgwywg", 11},
		{"bnebkn e avlidll n vemalt/gyywgw w wyggwyy w wgwywg", 10},
		{"tjmilo r agoailn l kneaia/gwwggg w ywggwyw w wgwyyg", 9},
		{"slropa m orodcht r ontreh/gwywgw w gyygwww w wgygwg", 8},
		{"onwigr o nrrtcra v rtxpee/gyyygy y wywgwyw w wgwywg", 7},
		{"socopr t ceatsen t amfeoy/gyyggy y wywgwww w ygwywg", 6},
		{"crmvpe r glaivye n belouy/ggwwgw w yywgwyw w wgwywg", 5},
		{"ndeeye e ltraeck a idnsks/gygygy y wwwgwyy w ygwywg", 4},
		{"speeda t ptocirn e mpeiey/gggwgw w yywgwyw g wgyywg", 3},
		{"scgoln n dindeer i uffare/gwwwgg w yyggwyw y wgwyyg", 2},
		{"fboueg i ulsoomg e loemna/gwwggw w wgygyyw y wgyywg", 1},
		{"bcstda a ieuotln e dnrloy/gwywgg y gwygyyw y wgwwwg", 0}, // Waffle's webpage review image
	}
)

type Stats struct {
	minPuzzle int
	maxPuzzle int
	dict      map[string]bool
	newWords  map[int]int
}

var (
	stats = Stats{
		0,
		0,
		map[string]bool{},
		map[int]int{},
	}
)

func recordPuzzle(index int, words []string, solved bool) {
	stats.minPuzzle = min(stats.minPuzzle, index)
	stats.maxPuzzle = max(stats.maxPuzzle, index)
	stats.newWords[index] = 0

	if !solved {
		stats.newWords[index] = 0
		return
	}
	for _, word := range words {
		if !stats.dict[word] {
			stats.newWords[index]++
		}
		stats.dict[word] = true
	}
}

func printStats() {
	fmt.Println()
	fmt.Println("Index,NewWords")
	for i := stats.minPuzzle; i <= stats.maxPuzzle; i++ {
		newWords, ok := stats.newWords[i]
		if !ok {
			newWords = -1
		}
		fmt.Printf("%d, %d\n", i, newWords)
	}
}

func dailyStats() {
	testCases := dailyWaffles
	for i := len(testCases) - 1; i >= 0; i-- {
		waffle := board.Parse(testCases[i].serial)
		s := solver.New(waffle)
		s.Solve()
		recordPuzzle(testCases[i].index, s.Words(), s.Solved())
	}
}

func TestSolve(testCases []TestCase) {
	total := 0
	count := 0
	for _, testCase := range testCases {
		waffle := board.Parse(testCase.serial)
		s := solver.New(waffle)
		if !s.Solve() {
			fmt.Println("Unable to solve:", testCase.serial)
			s.Print()
			fmt.Println()
			continue
		}
		path := pathfinder.New(s)
		path.Find()
		count++
		total += path.PathLen()
		fmt.Printf("Game: %3d Steps: %3d Average: %3.2f\n", testCase.index, path.PathLen(), float64(total)/float64(count))
	}
}

func TestParseSolution(testCases []TestCase) {
	for _, testCase := range testCases {
		waffle := board.Parse(testCase.serial)
		s := solver.New(waffle)
		if !s.Solve() {
			fmt.Println("Unable to solve:", testCase.serial)
			s.Print()
			fmt.Println()
			continue
		}
		puzzle := strings.Split(testCase.serial, "/")[0]
		solution := s.Serialize()
		signature := solver.ParseSolution(puzzle, solution)
		if signature != testCase.serial {
			s.Print()
			fmt.Printf("Failed to generate expected signature\n  Expected: %s\n  Got:      %s\n", testCase.serial, signature)
		}
		fmt.Printf("Game: %3d passes\n", testCase.index)
	}
}

func main() {
	statsOnly := flag.Bool("stats-only", false, "Only print word count stats")
	flag.Parse()

	if *statsOnly {
		dailyStats()
		printStats()
		return
	}

	fmt.Printf("Welcome to waffle regression tests!\n")

	fmt.Printf("\n---------- Quick sanity check ----------\n")

	fmt.Printf("\nDaily Waffles - ParseSolution\n")
	TestParseSolution(dailyWaffles[:2])

	fmt.Printf("\nDeluxe Waffles - ParseSolution\n")
	TestParseSolution(deluxeWaffles[:2])

	fmt.Printf("\nDaily Waffles\n")
	TestSolve(dailyWaffles[:2])

	fmt.Printf("\nDeluxe Waffles\n")
	TestSolve(deluxeWaffles[:2])

	fmt.Printf("\n---------- Exhaustive run of all tests ----------\n")

	fmt.Printf("\nDaily Waffles\n")
	TestSolve(dailyWaffles)

	fmt.Printf("\nDeluxe Waffles\n")
	TestSolve(deluxeWaffles)

	fmt.Printf("\nDaily Waffles - ParseSolution\n")
	TestParseSolution(dailyWaffles)

	fmt.Printf("\nDeluxe Waffles - ParseSolution\n")
	TestParseSolution(deluxeWaffles)
}
